// ---------------------------------------------------------------------------
// CODEF screen 490 — ported to Rust (no_std), running on the sealed ZigMachine.
//
// The screen is THE FABULOUS V8's intro for their crack of "Populous" (Atari ST),
// coded by Yoda. Ported from the CODEF HTML5 remake by Ayoros of Hemoroids, with
// the letter scroller by Totorman (wab.com screen 490, 16/03/2017, MIT). Graphics,
// scrolltext and the original intro are V8's; the tune is David Whittaker's
// "Custodian" (1989, SNDH rip by Grazey).
//
// Why this exists in Rust: it is the first real Rust screen, and it proves the
// Rust song-request bridge (apps/rust/zigmachine_music.rs) end to end. Nothing
// here is Zig: palette indices written into the shared video region, plus four
// exports the host polls for the tune.
//
// What the remake does (prototypes/codef/490/screen.js):
//   init_intro  AtariDecrunch, a fake Automation depacker (screen.js:160,173).
//               SKIPPED: ZigMachine depacks for real.
//   intro       the canvas flashes to white (alpha 0, +0.002/frame, while <= 0.1)
//   intro2      ...and back to black the same way                (screen.js:188)
//   go          fond_v8 every frame; from vbl 201, v8.png fading in and out over
//               400 frames; until vbl 150 the V8 logo still, then two scrollers
//               and the logo waving line by line                  (screen.js:221)
// The canvases are 640x400: an ST's 320x200 doubled, so no border is opened.
// ---------------------------------------------------------------------------
#![no_std]
#![no_main]

use core::panic::PanicInfo;
use core::ptr::addr_of_mut;

#[path = "../zigmachine_music.rs"]
mod zigmachine_music;
#[path = "../zigmachine_tvnoise.rs"]
mod zigmachine_tvnoise; // +/- tunes in through TV snow, as a Zig cart does
#[path = "v8_populous/fmath.rs"]
mod fmath;
#[path = "v8_populous/scroll.rs"]
mod scroll;

use fmath::{half, sin};
use scroll::{Totor, Wave, H, W};

// The remake loads "Custodian 1.ym" (screen.js:167), a YM5 dump. Subtune 1 of
// this SNDH writes the same YM registers (0-5, 8-10) on all 450 frames compared,
// one frame apart; subtunes 2-6 match none. FLAG ~y: no STE DMA, so it sounds.
const MUSIC: &str = "custodian.sndh";
const TUNE: u32 = 1;

#[link(wasm_import_module = "env")]
extern "C" {
    fn hwVideoBase() -> i32;
    fn consoleLogJS(ptr: *const u8, len: i32);
}

// Offsets into the video region: mirror machine/sdk/memmap.zig.
const OFF_PAL: usize = 0x0100;
const OFF_VRAM: usize = 0x1100;

// Generated by tools/private_tools/rust490_assets.py (see its header for formats).
const PAL: &[u8] = include_bytes!("../assets/screens/v8_populous/pal.bin");
const FOND: &[u8] = include_bytes!("../assets/screens/v8_populous/fond.bin");
const LOGO: &[u8] = include_bytes!("../assets/screens/v8_populous/logo.bin");
const ANIM: &[u8] = include_bytes!("../assets/screens/v8_populous/anim.bin");
const LOGO_W: usize = 55; // v8_logo.png is 110x140, tiles of 110x2 = one ST row each
const LOGO_ROWS: usize = 70;

const WAVE_TEXT: &[u8] = b" THE FABULOUS V EIGHT IS PROUD TO PRESENT YOU : POPULOUS  (WELL, IT SEEMS TO BE THE FINAL VERSION) CRACKED BY YODA  I AM THIS ONE THIS INTRO WAS BEEN CODED BY YODA.  HEY, BUDDIES HAVE YOU HEARD ABOUT US, BEFORE? WELL, I SUPPOSE YOU DIDN'T HUGH? O.K' TIME HAS COME FOR THINGS TO CHANGE IN THE WOLRD OF CRACKING COMPAGNIES, COZ WE'RE COMIN..... OH YEAH !..... AND NOW, I JUST WANNA SAY HELLO TO THE FRIENDS : COLONEL MUSTARD, RALPH, OZZY, CONNAN, SCANENRS, EVIL LORD, THE BASTARDS, BAD DUDES, UGLY JOE, OUTLANW, SKY FORCE, ETC... , AND FUCKS OFF TO ; RAVEN' COCKAKID THE ALLIGATOR WALTER WOLF ROGER RABBIT AND ALL THE WEIRDS OF THE HOLE WORLD        ";
const TOTOR_TEXT: &[u8] = b"   MEMBERS:                YODA                    ARIOCH                 DEMONIAK                  BLUE MAX                                ";

#[derive(PartialEq)]
enum Part {
    White,
    Black,
    Main,
}

struct Screen {
    video: usize,
    part: Part,
    grey: u8,      // the flashing canvas, uniform
    fade: f64,     // ONE global in the remake: intro's fade carries into go()'s v8 fade
    fade2: f64,
    vbl: u32,
    vbl_fade: u32,
    reprise: i32,  // reprise2: when the logo waves
    stop: f64,     // stop2: the wave amplitude, 0 or 5
    sin1: f64,     // mysin1_gd / mysin2_gd
    sin2: f64,
    wave: Wave,
    totor: Totor,
}

impl Screen {
    const fn new(video: usize) -> Screen {
        Screen {
            video, part: Part::White, grey: 0, fade: 0.0, fade2: 0.0, vbl: 0, vbl_fade: 0,
            reprise: -1, stop: 5.0, sin1: 0.0, sin2: 0.0,
            wave: Wave::new(WAVE_TEXT), totor: Totor::new(TOTOR_TEXT),
        }
    }

    fn vram(&self) -> &'static mut [u8] {
        // SAFETY: plane 0's 320x200 framebuffer inside the machine's video region.
        unsafe { core::slice::from_raw_parts_mut((self.video + OFF_VRAM) as *mut u8, (W * H) as usize) }
    }

    fn palette(&self) -> &'static mut [u8] {
        // SAFETY: plane 0's 256 x RGBA palette inside the machine's video region.
        unsafe { core::slice::from_raw_parts_mut((self.video + OFF_PAL) as *mut u8, 1024) }
    }

    /// intro()/intro2(): paint the whole canvas `target` at alpha `fade`, fade +=
    /// 0.002, and come back next frame while fade <= 0.1. False = that part is over
    /// and the next one starts in the SAME frame, as the JS calls straight into it.
    fn flash(&mut self, target: u8, second: bool) -> bool {
        let fade = if second { &mut self.fade2 } else { &mut self.fade };
        self.grey = blend(self.grey, target, *fade);
        *fade += 0.002;
        if *fade > 0.1 {
            return false;
        }
        let flash = ANIM[0] as usize;
        self.vram().fill(flash as u8);
        self.palette()[flash * 4..flash * 4 + 3].fill(self.grey);
        true
    }

    /// v8.png drawn at globalAlpha `alpha` over fond_v8. It only ever covers the
    /// background, so each (v8 colour, fond colour) pair is one palette entry, and
    /// the fade is a palette fade: exact per frame, and free.
    fn v8_alpha(&self, alpha: f64) {
        let pal = self.palette();
        for pair in ANIM[2..2 + 7 * ANIM[1] as usize].chunks_exact(7) {
            let i = pair[0] as usize * 4;
            for c in 0..3 {
                pal[i + c] = blend(pair[4 + c], pair[1 + c], alpha);
            }
        }
    }

    fn logo_row(&self, row: usize, left: f64, top: i32) {
        let (x0, y) = (half(left), half(f64::from(top)));
        if !(0..H).contains(&y) {
            return;
        }
        let vram = self.vram();
        for (k, &v) in LOGO[row * LOGO_W..][..LOGO_W].iter().enumerate() {
            let px = x0 + k as i32;
            if v != 0 && (0..W).contains(&px) {
                vram[(y * W + px) as usize] = v;
            }
        }
    }

    /// logo.drawTile(i, 316 + sin(s1)*stop2 + sin(s2)*stop2, 112 + 2i): 79 tiles,
    /// but the 110x140 image holds 70, so the last 9 draw nothing (and still turn
    /// the phases). The midhandle puts a tile's top-left at (x - 55, y - 1).
    fn wave_logo(&mut self) {
        self.reprise += 1;
        let (old1, old2) = (self.sin1, self.sin2);
        if self.reprise <= 40 { self.stop = 0.0; }
        if self.reprise > 41 && self.reprise <= 400 { self.stop = 5.0; }
        if self.reprise > 401 && self.reprise <= 700 { self.stop = 0.0; }
        if self.reprise > 701 { self.reprise = -1; }
        for i in 0..79 {
            if i < LOGO_ROWS {
                let x = 316.0 + sin(self.sin1) * self.stop + sin(self.sin2) * self.stop;
                self.logo_row(i, x - 55.0, 111 + 2 * i as i32);
            }
            self.sin1 += 0.2;
            self.sin2 += 0.3;
        }
        self.sin1 = old1 + 0.10;
        self.sin2 = old2 + 0.20;
    }

    /// go(), screen.js:221.
    fn main_part(&mut self) {
        self.vram().copy_from_slice(FOND); // fill black, then fond_v8 covers it all
        if self.vbl > 200 {
            self.v8_alpha(self.fade);
            if self.vbl_fade > 200 { self.fade -= 0.005; } else { self.fade += 0.005; }
            if self.vbl_fade > 400 { self.vbl_fade = 0; self.fade = 0.0; } else { self.vbl_fade += 1; }
        } else {
            self.v8_alpha(0.0);
        }
        if self.vbl <= 150 {
            for row in 0..LOGO_ROWS {
                self.logo_row(row, 316.0 - 55.0, 181 - 70 + 2 * row as i32);
            }
        } else {
            self.wave.draw(self.vram());
            self.wave_logo();
            self.totor.draw(self.vram());
        }
        // bloc.draw(0,0) is dropped: cache_letter.png is fond_v8's own corner.
        self.vbl += 1;
    }
}

/// One canvas draw at globalAlpha `alpha`, rounded to 8 bits. A globalAlpha
/// outside [0, 1] is IGNORED by the canvas, which keeps the 1 CODEF restored:
/// the v8 fade overshoots to 1.107 on its first cycle and draws opaque there.
fn blend(dst: u8, src: u8, alpha: f64) -> u8 {
    let a = if (0.0..=1.0).contains(&alpha) { alpha } else { 1.0 };
    fmath::floor(f64::from(src) * a + f64::from(dst) * (1.0 - a) + 0.5) as u8
}

static mut SCREEN: Screen = Screen::new(0);

fn screen() -> &'static mut Screen {
    // SAFETY: wasm32 carts are single-threaded and the host never re-enters.
    unsafe { &mut *addr_of_mut!(SCREEN) }
}

#[panic_handler]
fn panic(_: &PanicInfo) -> ! {
    loop {}
}

#[no_mangle]
pub extern "C" fn boot() {
    zigmachine_music::request_song_tune(MUSIC, TUNE);
    let s = screen();
    // SAFETY: a plain import from the machine; it returns the fixed region base.
    *s = Screen::new(unsafe { hwVideoBase() } as usize);
    s.palette().copy_from_slice(PAL);
    const MSG: &[u8] = b"screen 490 (V8 / Populous) - Rust cart, Custodian SNDH";
    // SAFETY: (ptr, len) names a 'static byte string.
    unsafe { consoleLogJS(MSG.as_ptr(), MSG.len() as i32) };
}

#[no_mangle]
pub extern "C" fn frame(_elapsed_ms: f32) {
    if zigmachine_tvnoise::step() {
        return; // a channel change: snow first
    }
    let s = screen();
    if s.part == Part::White {
        if s.flash(255, false) { return; }
        s.part = Part::Black;
    }
    if s.part == Part::Black {
        if s.flash(0, true) { return; }
        s.part = Part::Main;
    }
    s.main_part();
}

#[no_mangle]
pub extern "C" fn isPlaneEnabled(id: i32) -> i32 {
    (id == 0) as i32
}

// Optional ABI surface: no-op stubs so a keypress/HBL never hits a missing export.
#[no_mangle]
pub extern "C" fn hblDispatch(_id: u32, _plane: u32, _line: u32, _x: u32) {
    zigmachine_tvnoise::hbl();
}
#[no_mangle]
pub extern "C" fn skipBoot() {
    zigmachine_tvnoise::stop();
}
#[no_mangle]
pub extern "C" fn setShadeMode(_m: u32) {}
#[no_mangle]
pub extern "C" fn pointer(_x: i32, _y: i32, _b: u32) {}
#[no_mangle]
pub extern "C" fn input(_dir: u8) {}
