"""Assembles docs/ZIGMACHINE_GUIDE.html from the parsed sources and the prose."""
from __future__ import annotations

import re
from datetime import date

from . import ROOT, esc, unstamped
from .guide_body import render_chapter, render_consts, render_examples, render_items, slug
from .guide_content import INTRO
from .guide_sections import SECTIONS, Sec
from .guide_theme import TEMPLATE
from .zig_parse import Item, parse_consts, parse_externs, parse_struct_methods

GEOMETRY_RE = r"(?:WIDTH|HEIGHT|NB_PLANES|PHYSICAL_\w+|RASTER_\w+|MEDIUM_\w+|HORIZONTAL_\w+|VERTICAL_\w+|STRIDE_\w+)"

# The groups whose lengths are summed into the hero's "N library methods" and
# "N constants/registers" counts.
METHOD_KEYS = ("lfb", "zos", "blitter", "gui", "wm", "menubar", "dialog", "desktop", "mesh")
CONST_KEYS = ("geometry", "modes", "regs", "blit_regs", "blit_ctl")


def parse_sources() -> dict[str, list[Item]]:
    """Every generated reference group, parsed from the Zig sources it documents.
    GEM structs come from the files that DEFINE them: rom/gem/gui.zig only
    re-exports (`pub const Gui = core.Gui;`), which left five sections empty."""
    sdk = ROOT / "machine" / "sdk"
    mm = sdk / "memmap.zig"
    zigos = ROOT / "libs" / "zig" / "zigos.zig"
    gui = ROOT / "rom" / "gem" / "gui"
    return {
        "geometry": parse_consts(mm, GEOMETRY_RE),
        "modes": parse_consts(mm, r"(?:RES_\w+|FB_MODE_\w+)"),
        "regs": parse_consts(mm, r"REG_\w+"),
        # BLIT_CMD_* and BLIT_STATUS_BUSY are control values, listed once, below.
        "blit_regs": parse_consts(mm, r"BLIT_(?!CMD_|STATUS_BUSY)[A-Z_]+"),
        "blit_ctl": parse_consts(mm, r"(?:CON_\w+|MT_\w+|BLIT_CMD_\w+|BLIT_STATUS_\w+)"),
        "abi": parse_externs(sdk / "hardware.zig"),
        "lfb": parse_struct_methods(zigos, "LogicalFB"),
        "zos": parse_struct_methods(zigos, "ZigOS"),
        "blitter": parse_struct_methods(ROOT / "libs" / "zig" / "blitter.zig", "Blitter"),
        "gui": parse_struct_methods(gui / "core.zig", "Gui"),
        "wm": parse_struct_methods(gui / "window.zig", "Wm"),
        "menubar": parse_struct_methods(gui / "menu.zig", "MenuBar"),
        "dialog": parse_struct_methods(gui / "dialog.zig", "Dialog"),
        "desktop": parse_struct_methods(ROOT / "rom" / "gem" / "desktop" / "desktop.zig", "Desktop"),
        "mesh": parse_struct_methods(ROOT / "libs" / "zig" / "utils" / "obj_loader.zig", "Mesh"),
    }


def _body(sec: Sec, s: dict[str, list[Item]]) -> tuple[str, str]:
    """A section's rendered body and its count badge."""
    if sec.kind == "md":
        return render_chapter(sec.src, slug(sec.title)), ""
    items = s[sec.src]
    if sec.kind == "consts":
        return render_consts(items), f"{len(items)} entr{'y' if len(items) == 1 else 'ies'}"
    noun = "export" if sec.src == "abi" else "method"
    return render_items(items, sec.prefix), f"{len(items)} {noun}{'' if len(items) == 1 else 's'}"


def render_section(sec: Sec, body: str, count: str) -> str:
    badge = f'<span class="count">{count}</span>' if count else ""
    return (
        f'<section class="ref" id="{slug(sec.title)}">'
        f'<header class="sec-h"><span class="eyebrow">{esc(sec.group)}</span>'
        f"<h2>{esc(sec.short)}<small>{esc(sec.sub)}</small></h2>{badge}</header>"
        f"{body}</section>"
    )


def rail() -> str:
    out = ['<div class="rail-g">Start</div>',
           '<a href="#top" data-slug="top">Overview</a>',
           '<a href="#examples" data-slug="examples">Examples</a>']
    group = ""
    for sec in SECTIONS:
        if sec.group != group:
            group = sec.group
            out.append(f'<div class="rail-g">{esc(group)}</div>')
        out.append(f'<a href="#{slug(sec.title)}" data-slug="{slug(sec.title)}">{esc(sec.short)}</a>')
    return "\n".join(out)


def stats(s: dict[str, list[Item]]) -> str:
    methods = sum(len(s[k]) for k in METHOD_KEYS)
    consts = sum(len(s[k]) for k in CONST_KEYS)
    tiles = [
        (len(s["abi"]), "ABI exports", "hw-abi-machine-exports"),
        (methods, "library methods", "zigos-logicalfb-a-plane"),
        (consts, "constants / registers", "geometry-resolution"),
    ]
    return "".join(f'<li><a href="#{a}"><b>{n}</b>{label}</a></li>' for n, label, a in tiles)


def build() -> str:
    s = parse_sources()
    sections = "\n".join(render_section(sec, *_body(sec, s)) for sec in SECTIONS)
    return TEMPLATE.format(
        rail=rail(),
        stats=stats(s),
        intro=INTRO,
        date=date.today().isoformat(),
        examples=render_examples(),
        sections=sections,
    )


GENERATED_LINE = re.compile(r"Generated \d{4}-\d{2}-\d{2} by tools/gen_docs\.py")


def undated(text: str) -> str:
    """The guide minus its generation date, which changes every day by itself,
    and minus cache_bust.py's ?v= stamps, which it rewrites after generation."""
    return unstamped(GENERATED_LINE.sub("Generated by tools/gen_docs.py", text))
