const std = @import("std");

const page_size = 65536; // in bytes

// Video shared main-thread memory (see machine/sdk/memmap.zig): machine-video.wasm +
// demo.wasm import the SAME WebAssembly.Memory; demo linked above the machine.
const video_shared_bytes = 112 * page_size; // 7 MiB (2 MiB demo window + VRAM + PFB + the 2 MiB ROM window; see memmap SHARED_PAGES)
const demo_global_base: u64 = 0x100000; // 1 MiB
const machine_stack = 1 * page_size;
const demo_stack = 6 * page_size;
// The ROM chip's own window (memmap ROM_RAM_BASE/TOP): 2 MiB at 5 MiB.
const rom_global_base: u64 = 0x500000;
const rom_stack = 4 * page_size;

// Audio shared worklet-thread memory (see machine/sdk/audio.zig).
const audio_bytes = 48 * page_size;
const audio_demo_base: u64 = 0x100000;

pub fn build(b: *std.Build) void {
    const build_wasm = b.option(bool, "wasm", "Build the wasm libraries.") orelse false;
    // Kept for compatibility with the old `-Drelease=true` invocation.
    const release = b.option(bool, "release", "Build in ReleaseSmall mode.") orelse false;
    const optimize: std.builtin.OptimizeMode = if (release) .ReleaseSmall else b.standardOptimizeOption(.{});

    if (!build_wasm) return;

    const wasm_target = b.resolveTargetQuery(.{
        .cpu_arch = .wasm32,
        .os_tag = .freestanding,
        .abi = .musl,
    });

    // ----------------------------------------------------------------------
    // Shared modules — the SEAL is enforced here: the open `apps`/`zigos` code
    // reaches the machine ONLY through the `hardware`/`audio_hw` SDK headers
    // (machine/sdk/*), never machine/ source.
    // ----------------------------------------------------------------------
    const sdk_video = b.createModule(.{
        .root_source_file = b.path("machine/sdk/hardware.zig"),
        .target = wasm_target,
        .optimize = optimize,
    });
    const sdk_audio = b.createModule(.{
        .root_source_file = b.path("machine/sdk/audio.zig"),
        .target = wasm_target,
        .optimize = optimize,
    });
    const zigos_mod = b.createModule(.{
        .root_source_file = b.path("libs/zig/zigos.zig"),
        .target = wasm_target,
        .optimize = optimize,
        .imports = &.{.{ .name = "hardware", .module = sdk_video }},
    });
    // TV analogue snow shown while a channel (+/- on the monitor) tunes in; pure,
    // so demo_main owns the plane and this stays natively testable. Its own
    // directory: a module rooted in effects/ would claim files zigos imports.
    const tvnoise_mod = b.createModule(.{
        .root_source_file = b.path("libs/zig/tvnoise/tvnoise.zig"),
        .target = wasm_target,
        .optimize = optimize,
    });
    // Runtime depackers (Pack-Ice &c). ST files arrive crunched, and opening one
    // is the machine's job, not a build step's.
    const depackers_mod = b.createModule(.{
        .root_source_file = b.path("libs/zig/depackers/depackers.zig"),
        .target = wasm_target,
        .optimize = optimize,
    });
    // Cart assets that ship ZX0-packed (libs/zig/depackers/zx0.zig, docs/DEPACK.md).
    // zx0pack runs on the HOST at build time, so a packed asset can never drift
    // from its source; a scene reaches it as @import("packed_assets").<name> and
    // depacks it at run time, with the effect chosen here (--fx).
    const zx0pack = b.addExecutable(.{
        .name = "zx0pack",
        .root_module = b.createModule(.{
            .root_source_file = b.path("tools/zx0pack/main.zig"),
            .target = b.graph.host,
            .optimize = .ReleaseFast,
            .imports = &.{.{ .name = "zx0_pack", .module = b.createModule(.{
                .root_source_file = b.path("libs/zig/depackers/zx0_pack.zig"),
                .target = b.graph.host,
                .optimize = .ReleaseFast,
            }) }},
        }),
    });
    // Also installed (zig-out/bin/zx0pack) so build.sh can pack every asset and
    // report the ratios (tools/pack_stats.sh).
    b.installArtifact(zx0pack);
    const pack_trsi = b.addRunArtifact(zx0pack);
    pack_trsi.addArgs(&.{ "--fx", "rasters" });
    pack_trsi.addFileArg(b.path("apps/zig/assets/screens/union_intro/trsi_turn.raw"));
    const trsi_zx0 = pack_trsi.addOutputFileArg("trsi_turn.zx0");
    const packed_files = b.addWriteFiles();
    _ = packed_files.addCopyFile(trsi_zx0, "trsi_turn.zx0");
    const packed_assets_mod = b.createModule(.{
        .root_source_file = packed_files.add("packed_assets.zig",
            \\// Generated by build.zig: ZX0-packed cart assets.
            \\pub const trsi_turn = @embedFile("trsi_turn.zx0");
            \\
        ),
        .target = wasm_target,
        .optimize = optimize,
    });
    const players_mod = b.createModule(.{
        .root_source_file = b.path("libs/zig/players/players.zig"),
        .target = wasm_target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "audio_hw", .module = sdk_audio },
            .{ .name = "depackers", .module = depackers_mod },
        },
    });
    // The SNDH player needs a 68000, because an SNDH IS 68000 code: Musashi runs
    // it and libs/zig/players/sndh_player.zig traps its PSG writes to the sealed
    // YM chip. Musashi's opcode table is machine-generated, so m68kmake is built
    // for the HOST and run here rather than checking 800 KB of C into the repo.
    addMusashi(b, players_mod);
    // rom/ — reference system software (GEM). Linked into rom.wasm (rom_chip
    // below), NOT into carts: a cart gets rom_sdk, the flat ABI header.
    const rom_mod = b.createModule(.{
        .root_source_file = b.path("rom/rom.zig"),
        .target = wasm_target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zigos", .module = zigos_mod },
            .{ .name = "hardware", .module = sdk_video },
        },
    });
    // rom/sdk/ — the FLAT, app-facing ROM ABI. Apps import this as `rom_sdk`; only
    // numbers cross its entry points, which is what lets the bodies live in
    // rom.wasm (see rom_chip below) and lets a C or Rust app call GEM.
    const rom_sdk_mod = b.createModule(.{
        .root_source_file = b.path("rom/sdk/rom.zig"),
        .target = wasm_target,
        .optimize = optimize,
        // NO `rom` import: this is a pure header of `extern` declarations now, and
        // an app that linked the ROM's internals would defeat the whole split.
        .imports = &.{
            .{ .name = "zigos", .module = zigos_mod },
            .{ .name = "hardware", .module = sdk_video },
        },
    });

    // rom.wasm — the ROM CHIP. Its own module, its own RAM window above the video
    // region, linked against the sealed HW ABI exactly like a cart. It exports the
    // flat ABI declared in rom/sdk/rom.zig; the host wires an app's env to it.
    const rom_chip = b.addExecutable(.{
        .name = "rom",
        .root_module = b.createModule(.{
            .root_source_file = b.path("rom/rom_main.zig"),
            .target = wasm_target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zigos", .module = zigos_mod },
                .{ .name = "rom", .module = rom_mod },
                .{ .name = "hardware", .module = sdk_video },
                // romDepack: a disk's cart is stored ZX0-packed and the ROM unpacks it.
                .{ .name = "depackers", .module = depackers_mod },
            },
        }),
    });
    rom_chip.entry = .disabled;
    rom_chip.rdynamic = true;
    rom_chip.import_memory = true;
    rom_chip.stack_size = rom_stack;
    rom_chip.initial_memory = video_shared_bytes;
    rom_chip.max_memory = video_shared_bytes;
    rom_chip.global_base = rom_global_base;
    b.getInstallStep().dependOn(&b.addInstallFileWithDir(
        rom_chip.getEmittedBin(), .{ .custom = "../docs" }, "rom.wasm").step);

    // machine/boot.zig — the boot ROM (POST screen). Machine firmware: depends ONLY
    // on the HW ABI, no libs. Still app-linked into every cart; moving it inside
    // machine-video.wasm is an open idea, unrelated to the ROM chip.
    const boot_rom_mod = b.createModule(.{
        .root_source_file = b.path("machine/boot.zig"),
        .target = wasm_target,
        .optimize = optimize,
        .imports = &.{.{ .name = "hardware", .module = sdk_video }},
    });

    const sealed_step = b.step("sealed", "Compiles the sealed machine + open demo wasm");

    const installTo = struct {
        fn add(bld: *std.Build, art: *std.Build.Step.Compile, step: *std.Build.Step) void {
            const inst = bld.addInstallArtifact(art, .{ .dest_dir = .{ .override = .{ .custom = "../docs" } } });
            bld.getInstallStep().dependOn(&inst.step);
            step.dependOn(&inst.step);
        }
    }.add;

    // ----------------------------------------------------------------------
    // machine/ — SEALED machine binaries (single module root each; no SDK imports)
    // ----------------------------------------------------------------------
    const machine_video = b.addExecutable(.{
        .name = "machine-video",
        .root_module = b.createModule(.{
            .root_source_file = b.path("machine/machine_video.zig"),
            .target = wasm_target,
            .optimize = optimize,
        }),
    });
    machine_video.entry = .disabled;
    machine_video.rdynamic = true;
    machine_video.import_memory = true;
    machine_video.stack_size = machine_stack;
    machine_video.initial_memory = video_shared_bytes;
    machine_video.max_memory = video_shared_bytes;
    installTo(b, machine_video, sealed_step);

    const machine_audio = b.addExecutable(.{
        .name = "machine-audio",
        .root_module = b.createModule(.{
            .root_source_file = b.path("machine/machine_audio.zig"),
            .target = wasm_target,
            .optimize = optimize,
        }),
    });
    machine_audio.entry = .disabled;
    machine_audio.rdynamic = true;
    machine_audio.import_memory = true;
    machine_audio.stack_size = machine_stack;
    machine_audio.initial_memory = audio_bytes;
    machine_audio.max_memory = audio_bytes;
    installTo(b, machine_audio, sealed_step);

    // ----------------------------------------------------------------------
    // apps/zig/ — OPEN coder binaries (import zigos / rom / players / audio_hw)
    // ----------------------------------------------------------------------
    // Cartridge matrix: the menu launcher (demo.wasm) + one cart per scene
    // (demo-<tag>.wasm). Each shares apps/zig/demo_main.zig; its `cart` module is
    // the scene (or the menu), whose entry demo_main auto-detects. Keep in sync
    // with apps/zig/scenes/catalog.zig (menu list) and tools/pack_floppies.sh.
    // Cart names, index-aligned with the switch in apps/zig/cart.zig and the tags
    // in apps/zig/scenes/catalog.zig. Index 0 is the menu launcher (demo.wasm).
    // An "" entry EXCLUDES a cart from the build (the index is kept, so it stays
    // aligned with cart.zig and catalog.zig). None are excluded today.
    const cart_names = [_][]const u8{
        "demo",              "demo-union_intro",
        "demo-union_main",   "demo-music",
        "demo-blitter",      "demo-scroll",      "demo-obj",        "demo-gem",
        "demo-st_replay",    "demo-ancool",      "demo-bladerunners", "demo-dbug",
        "demo-deltaforce",   "demo-deltaforce2", "demo-empire",     "demo-equinox",
        "demo-fallen_angels", "demo-fullscreen", "demo-ics",        "demo-leonard",
        "demo-maxi",         "demo-medium_overscan",
        "demo-res_switch",   "demo-shapes",
        "demo-stcs",         "demo-tex",
        "demo-badflicker", // 26 — overscan trick done wrong (raw pokes, off-column)
        "demo-stream", // 27 — block-streams a sample off the disk
        "demo-noextra", // 28 — NoExtra Team / DHS Megademo 2005 (CODEF screen 198)
        "demo-replicants_dd2", // 29 — Replicants / Double Dragon II (CODEF screen 515)
        "demo-supplex_fs2", // 30 — Supplex / Flight Simulator II NDD (CODEF screen 525)
        "demo-replicants_garfield", // 31 — The Replicants / Garfield (CODEF screen 28)
        "demo-ulm_spoon_distorter", // 32 — ULM / Dark Side of the Spoon, Parallax Distorter (CODEF screen 287)
        "demo-replicants", // 33 — REPS OLD: the pre-CODEF Replicants/Garfield, kept to compare with 31
        "demo-cuddly_starwars", // 34 — The Carebears / Starwars Scroller, Cuddly Demos (CODEF screen 360)
        "demo-replicants_kickoff2", // 35 — The Replicants / Kick Off 2 crack intro (CODEF screen 168)
        "demo-dyno_paradis3", // 36 — Dyno / ParaDis3, Parallax Distorter (CODEF screen 470)
        "demo-mandelbrot", // 37 — the fractal channel from the original gh-page
        "demo-stniccc", // 38 — Oxygene / STNICCC 2000, the polygon flight (scene1.bin stream)
        "demo-tex_neoshow", // 39 — The Exceptions / Super Neo Demo Show (CODEF screen 473)
        "demo-elite_snooker", // 40 — ELITE / Jimmy White Snooker crack intro (CODEF screen 422)
        "demo-union_demo", // 41 — The Union / Union Demo main menu (melonJS remake hub)
    };
    for (cart_names, 0..) |name, idx| {
        if (name.len == 0) continue; // excluded cart (see note above)
        const cart_opts = b.addOptions();
        cart_opts.addOption(usize, "index", idx);
        const cart_mod = b.createModule(.{
            .root_source_file = b.path("apps/zig/cart.zig"),
            .target = wasm_target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zigos", .module = zigos_mod },
                // NO `rom`: a cart links the ROM's flat ABI header, never its
                // internals — those live in rom.wasm now. Handing rom_mod to carts
                // made the separation a convention that one @import("rom") could
                // silently undo, re-linking the whole toolkit into that cart.
                .{ .name = "rom_sdk", .module = rom_sdk_mod },
                // The HW ABI header (not machine source) — lets a scene poke sealed
                // registers directly, ST-style (e.g. scenes/badflicker.zig).
                .{ .name = "hardware", .module = sdk_video },
                .{ .name = "cart_opts", .module = cart_opts.createModule() },
                // Run-time depackers + the assets build.zig packs (see zx0pack above).
                .{ .name = "depackers", .module = depackers_mod },
                .{ .name = "packed_assets", .module = packed_assets_mod },
            },
        });
        const exe = b.addExecutable(.{
            .name = name,
            .root_module = b.createModule(.{
                .root_source_file = b.path("apps/zig/demo_main.zig"),
                .target = wasm_target,
                .optimize = optimize,
                .imports = &.{
                    .{ .name = "zigos", .module = zigos_mod },
                    .{ .name = "rom_sdk", .module = rom_sdk_mod }, // the ABI, not the ROM
                    .{ .name = "boot_rom", .module = boot_rom_mod },
                    .{ .name = "cart", .module = cart_mod },
                    .{ .name = "tvnoise", .module = tvnoise_mod },
                },
            }),
        });
        exe.entry = .disabled;
        exe.rdynamic = true;
        exe.import_memory = true;
        exe.stack_size = demo_stack;
        exe.initial_memory = video_shared_bytes;
        exe.max_memory = video_shared_bytes;
        exe.global_base = demo_global_base;
        installTo(b, exe, sealed_step);
    }

    // Executable boot-sector programs (ZigCart format v2): bare wasm — no ZigOS/ROM,
    // they poke the sealed video ABI directly and must stay tiny (≤ 1 KB boot sector).
    // Packed into a disk's block 0 by mkdisk (which tunes the $1234 checksum word).
    const boot_progs = [_][]const u8{"novirus"};
    for (boot_progs) |bp| {
        const exe = b.addExecutable(.{
            .name = b.fmt("boot-{s}", .{bp}),
            .root_module = b.createModule(.{
                .root_source_file = b.path(b.fmt("apps/zig/boot/{s}.zig", .{bp})),
                .target = wasm_target,
                .optimize = optimize,
                .imports = &.{.{ .name = "hardware", .module = sdk_video }},
            }),
        });
        exe.entry = .disabled;
        exe.rdynamic = true;
        exe.import_memory = true;
        exe.stack_size = demo_stack;
        exe.initial_memory = video_shared_bytes;
        exe.max_memory = video_shared_bytes;
        exe.global_base = demo_global_base;
        installTo(b, exe, sealed_step);
    }

    const demo_audio = b.addExecutable(.{
        .name = "demo-audio",
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/zig/demo_audio_main.zig"),
            .target = wasm_target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "audio_hw", .module = sdk_audio },
                .{ .name = "players", .module = players_mod },
            },
        }),
    });
    demo_audio.entry = .disabled;
    demo_audio.rdynamic = true;
    demo_audio.import_memory = true;
    demo_audio.stack_size = 2 * page_size;
    demo_audio.initial_memory = audio_bytes;
    demo_audio.max_memory = audio_bytes;
    demo_audio.global_base = audio_demo_base;
    installTo(b, demo_audio, sealed_step);
}

// Musashi (kstenerud, MIT — see libs/c/musashi/README.md) compiled into a module
// as the 68000 the SNDH player drives.
//
// Its opcode table is machine-generated, so m68kmake is built for the HOST and
// run here rather than checking 800 KB of generated C into the repo. Include
// order matters: config/ shadows upstream's m68kconf.h with our 68000-only
// settings, freestanding/ supplies the few libc headers wasm32-freestanding
// lacks, and the generated m68kops.h has to be findable as well.
fn addMusashi(b: *std.Build, mod: *std.Build.Module) void {
    const maker = b.addExecutable(.{
        .name = "m68kmake",
        .root_module = b.createModule(.{ .target = b.graph.host, .optimize = .ReleaseFast }),
    });
    maker.root_module.addCSourceFile(.{
        .file = b.path("libs/c/musashi/upstream/m68kmake.c"),
        .flags = &.{"-w"}, // 1998 C, and not ours to clean up
    });
    maker.root_module.link_libc = true;

    const run = b.addRunArtifact(maker);
    const generated = run.addOutputDirectoryArg("musashi");
    run.addFileArg(b.path("libs/c/musashi/upstream/m68k_in.c"));

    mod.addIncludePath(b.path("libs/c/musashi/config"));
    mod.addIncludePath(b.path("libs/c/musashi/freestanding"));
    mod.addIncludePath(b.path("libs/c/musashi/upstream"));
    mod.addIncludePath(generated);

    // Absolute: a relative -include lands in the compilation's dependency list
    // as a path the cache cannot resolve, and every C step fails CacheCheckFailed.
    const config_h = b.pathJoin(&.{ b.build_root.path.?, "libs/c/musashi/config/zm_musashi.h" });
    const flags = [_][]const u8{ "-ffreestanding", "-fno-builtin", "-w", "-include", config_h };
    mod.addCSourceFile(.{ .file = generated.path(b, "m68kops.c"), .flags = &flags });
    mod.addCSourceFile(.{ .file = b.path("libs/c/musashi/upstream/m68kcpu.c"), .flags = &flags });
    mod.addCSourceFile(.{ .file = b.path("libs/c/musashi/upstream/softfloat/softfloat.c"), .flags = &flags });
    mod.addCSourceFile(.{ .file = b.path("libs/c/musashi/freestanding/stubs.c"), .flags = &flags });
}
