// Generated by tools/union_main_assets.py from assets/oldies/UnionDemoCracktro/intro/efmain.js — do not hand-edit.

pub const WORLD_W: usize = 802;
pub const WORLD_ROWS: usize = 9;
pub const ANIM_ROWS: usize = 5;
pub const POS_DOORS = [_]u16{ 21, 47, 79, 119, 157, 201, 247, 333, 357, 395, 433, 471, 507, 559, 619, 649, 677, 721 };
