// The scrolltexts of CODEF screen 295, copied VERBATIM from screen.js by
// tools/private_tools/swedish_newyear_texts.py (the remake's own words, typos kept).

pub const menu = " HELLO AND WELCOME TO THE SWEDISH NEW YEAR DEMO, RELEASED THE 01-01-1989 (A.C.)    PRESS F" ++
    "1-SYNC  F2-THE CAREBEARS (VERY VERY GOOD DEMO) (GUESS WHO WROTE THAT)  F3-OMEGA  F4-F10 DO" ++
    "N'T WORK      THE CREDITS:  OMEGA FOR GRAPHIXX, THE CAREBEARS FOR RECODING (WITHOUT ANY BU" ++
    "GS) AND PUTTING EVERYTHING TOGETHER (AND JAS FOR CHOOSING THE PALETTE FOR THE SCROLLTEXT) " ++
    "AND MAD MAX FOR THE MUZAK. IF YOU READ THIS TEN TIMES WE WILL TELL YOU HOW TO REMOVE ALL O" ++
    "F THE BORDERS.    ";
// menutext: 468 characters
pub const omega = "            HI TO ALL YOU PEOPLE OUT THERE ! MY NAME IS ' THE FLYING EGG ' , AND MAYBE YOU" ++
    "'VE HEARD OF ME, AND MAYBE NOT. BUT WHO CARES?        WELL , AS YOU HAVE SEEN , WE ( HAQ, " ++
    "JVA, RED, KMA, TFE ) , THE CAREBEARS AND AN COOL , AND SYNC HAVE MADE A COPY PARTY DEMO . " ++
    "WHERE IN WHICH WE HAVE MADE THE SCREEN THAT YOU ARE LOOKING AT RIGHT NOW. WHEN WE GOT TO T" ++
    "HE COPY PARTY, THE OTHER CREWS ALREADY HAD BEGUN MAKING THEIR DEMOS. SO IN APPROXIMATELY 1" ++
    "2 HOURS, RED AND I ( THE FLYING EGG ) WORKED REALLY HARD , STARTING WITH NOTHING, WE ENDED" ++
    " UP WITH A DEMO WHICH WASN'T TOO BAD , WITH THE LED VOLUME DISPLAYS IN THE LOWER BORDER , " ++
    "FLASHING DRIVE INDICIATOR , AND SOME NICE GRAPHICS ( MADE BY RED , THE PAINTER IN OMEGA )." ++
    " THE MUSIC YOU HEAR COMES FROM THE GAME ' BEYOND THE ICE PALACE ' , AND THE REASON WHY WE " ++
    "PICKED THAT SONG IS THAT IT GAVE THE BEST REACTION ON THE LED VOLUME DISPLAYS, AND WE GOT " ++
    "THE BEST RESULT WITH CONTROLLING THE DRIVE INDICATOR ON THAT SONG TOO. AND AT LAST , WE TH" ++
    "OUGHT IT WASN'T THAT BAD AT ALL. WHEN I WRITE THIS MESSAGE I'M SITTING IN A BIG CLASSROOM " ++
    "IN A SWEDISH CITY CALLED ' ANGELHOLM ' WITH TWO DOTS OVER THE ' A '. THE CAREBEARS ARE SIT" ++
    "TING RIGHT IN FRONT OF ME , AND THEY ARE WRITING THEIR SCROLLINE TOO. BUT THEY HAVE WRITTE" ++
    "N MORE TEXT THAN I HAVE , SO I'D BETTER START WRITING FASTER. THE ONLY PROBLEM I GOT IS TH" ++
    "AT I CAN NOT OF ANYTHING TO WRITE ABOUT THAT MAKES ANY SENSE. SO I JUST KEEP ON WRITING SO" ++
    "ME BULLSHIT UNTIL SOMEONE COME AND STOPS ME FROM WRITING , BUT I WOULD BE SO SAD IF I COUL" ++
    "DN'T FEEL THE PRESSURE OF THE BUTTONS UNDER MY FINGERS, SO I WOULD PROBABLY JUMP OUT OF A " ++
    "WINDOW , AND THEN I WOULDN'T BE ABLE TO WRITE MORE TEXT , AND YOU DON'T WANT ME TO STOP WR" ++
    "ITING ? DO YOU ? NO I THOUGHT SO , SO HERE COMES EVEN MORE BULLSHIT.....................  " ++
    "                     ";
// otext: 1821 characters
