// The menu scrolltext of CODEF screen 295, copied VERBATIM from screen.js by
// tools/private_tools/swedish_newyear_texts.py (the remake's own words, typos kept).

pub const menu = " HELLO AND WELCOME TO THE SWEDISH NEW YEAR DEMO, RELEASED THE 01-01-1989 (A.C.)    PRESS F" ++
    "1-SYNC  F2-THE CAREBEARS (VERY VERY GOOD DEMO) (GUESS WHO WROTE THAT)  F3-OMEGA  F4-F10 DO" ++
    "N'T WORK      THE CREDITS:  OMEGA FOR GRAPHIXX, THE CAREBEARS FOR RECODING (WITHOUT ANY BU" ++
    "GS) AND PUTTING EVERYTHING TOGETHER (AND JAS FOR CHOOSING THE PALETTE FOR THE SCROLLTEXT) " ++
    "AND MAD MAX FOR THE MUZAK. IF YOU READ THIS TEN TIMES WE WILL TELL YOU HOW TO REMOVE ALL O" ++
    "F THE BORDERS.    ";
// menutext: 468 characters
