// --------------------------------------------------------------------------
// Union intro — efmain_intro placement animation data table.
// Hand-transcribed 1:1 from assets/oldies/UnionDemoCracktro/intro/efmain_intro.js
// (this.backlayersData), halved (oriX/Y, speedX/Y, destX/Y /2 — same canvas
// 768x540 -> 400x280 half-scale convention as the rest of the Union port;
// frame counts are NOT halved, the animation still runs 1 step/frame @60Hz).
//
// Image data + palette ranges are GENERATED by tools/union_intro_assets.py
// into placement_dims.zig — do not hand-edit those, only this physics table.
// --------------------------------------------------------------------------
const dims = @import("../../assets/screens/union_intro/placement/placement_dims.zig");

pub const Kind = enum { scroll, fade, anim };

pub const StripDef = struct {
    raw: []const u8,
    w: u16,
    h: u16,
    lo: u8, // first palette index owned by this strip (placement.pal)
    hi: u8, // last palette index owned by this strip (inclusive)
    ox: f32, // origin position (halved canvas units)
    oy: f32,
    sx: f32, // speed (halved units/frame)
    sy: f32,
    dx: f32, // destination (clamp target, halved units)
    dy: f32,
    dirx: i8,
    diry: i8,
    kind: Kind,
    alpha0: f32,
};

const RAWS = [17][]const u8{
    @embedFile("../../assets/screens/union_intro/placement/back_layer0.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer1.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer2.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer3.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer4.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer5.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer6.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer7.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer8.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer9.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer10.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer11.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer12.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer13.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer14.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer15.raw"),
    @embedFile("../../assets/screens/union_intro/placement/back_layer16.raw"),
};

fn def(i: usize, ox: f32, oy: f32, sx: f32, sy: f32, dx: f32, dy: f32, dirx: i8, diry: i8, kind: Kind, alpha0: f32) StripDef {
    return .{
        .raw = RAWS[i],
        .w = dims.STRIP_DIMS[i][0],
        .h = dims.STRIP_DIMS[i][1],
        .lo = dims.STRIP_RANGE[i][0],
        .hi = dims.STRIP_RANGE[i][1],
        .ox = ox,
        .oy = oy,
        .sx = sx,
        .sy = sy,
        .dx = dx,
        .dy = dy,
        .dirx = dirx,
        .diry = diry,
        .kind = kind,
        .alpha0 = alpha0,
    };
}

// oriX,oriY,speedX,speedY,destX,destY,dirX,dirY,alpha0,kind — halved from the JS source.
pub const STRIPS = [17]StripDef{
    def(0, -384, 0, 5, 0, 0, 0, 1, 0, .scroll, 1.0), // top sky
    def(1, 768, 13, 5, 0, 0, 13, -1, 0, .scroll, 1.0),
    def(2, 484, 32, 4, 0, 0, 32, -1, 0, .scroll, 1.0),
    def(3, -584, 48, 8, 0, 0, 48, 1, 0, .scroll, 1.0),
    def(4, 434, 64, 3, 0, 0, 64, -1, 0, .scroll, 1.0),
    def(5, -434, 80, 8, 0, 0, 80, 1, 0, .scroll, 1.0),
    def(6, 384, 96, 2.5, 0, 0, 96, -1, 0, .scroll, 1.0),
    def(7, -768, 112, 8, 0, 0, 112, 1, 0, .scroll, 1.0), // low sky
    def(8, 0, -600, 0, 8, 0, 78, 0, 1, .scroll, 1.0), // low-sky sprites (world)
    def(9, 0, 450, 0, 4, 0, 142, 0, -1, .scroll, 1.0), // floor
    def(10, 0, 600, 0, 8, 0, 174, 0, -1, .scroll, 1.0), // ground top
    def(11, 0, 800, 0, 8, 0, 190, 0, -1, .scroll, 1.0), // ground bottom
    def(12, 0, 206, 0, 0, 0, 206, 0, 0, .fade, 0.001), // bottom
    def(13, 0, 30, 0, 0, 0, 30, 0, 0, .fade, 0.001), // high clouds
    def(14, 384, 46, 5, 0, 0, 46, -1, 0, .scroll, 1.0),
    def(15, 0, 500, 0, 5, 0, 62, 0, -1, .scroll, 1.0), // low clouds
    def(16, -500, 114, 3.5, 0, 192, 114, 1, 0, .anim, 1.0), // runner sprite sheet
};
