// Generated by tools/private_tools/union_demo_assets.py -- do not hand-edit.
// Shared-palette slots the scene addresses by name.
pub const FONT_FIELD: u8 = 18; // fontsTexOut2's opaque field
pub const BLACK: u8 = 6;
pub const WHITE: u8 = 33;
