// Generated by tools/private_tools/union_demo_assets.py from the remake's
// data/union3.tmx (Tiled, 175x25 tiles of 32x16) -- do not hand-edit.
// Coordinates are the ORIGINAL 640-wide map pixels; the scene halves on draw.

pub const COLS: usize = 175;
pub const ROWS: usize = 25;
pub const TILE_W: u16 = 32;
pub const TILE_H: u16 = 16;
pub const START_X: f32 = 268;
pub const START_Y: f32 = 180;

/// One DoorEntity from the TMX "Doors" object group, in file order.
pub const DoorRect = struct { x: f32, y: f32, w: f32, h: f32, demo_name: []const u8 };
pub const DOORS = [_]DoorRect{
    .{ .x = 672, .y = 112, .w = 96, .h = 112, .demo_name = "BEATDIS_LOADER" },
    .{ .x = 1312, .y = 112, .w = 96, .h = 112, .demo_name = "DELTAFORCE_LOADER" },
    .{ .x = 1600, .y = 112, .w = 96, .h = 112, .demo_name = "TNT3_LOADER" },
    .{ .x = 1824, .y = 112, .w = 96, .h = 112, .demo_name = "SUPERSCROLLER_LOADER" },
    .{ .x = 2624, .y = 112, .w = 96, .h = 112, .demo_name = "TNT1_LOADER" },
    .{ .x = 3008, .y = 112, .w = 96, .h = 112, .demo_name = "REPS_LOADER" },
    .{ .x = 3520, .y = 112, .w = 96, .h = 112, .demo_name = "TNT2_LOADER" },
    .{ .x = 3936, .y = 113, .w = 96, .h = 112, .demo_name = "L16_LOADER" },
    .{ .x = 4224, .y = 112, .w = 96, .h = 112, .demo_name = "MULTIFAKE_LOADER" },
    .{ .x = 5442, .y = 112, .w = 96, .h = 112, .demo_name = "COPIER_LOADER" },
    .{ .x = 2208, .y = 112, .w = 96, .h = 112, .demo_name = "TEXTRACKER_LOADER" },
};
