"""mkassets.py OUTDIR: the dune_gen4 cart's assets, straight from the disk and DUNE.PRG.

Copies the disk files the cart embeds as they are (the Tiny pictures, the fonts,
BLACK.DAT, XYEAGLE.DAT) and writes tables.zig: every table the screens are driven by,
read out of the depacked program (dune_unpacked.prg, `python3 unjek.py`) at the TEXT
offset named in its comment. Nothing is retyped.
"""
import os
import shutil
import struct
import sys

out = sys.argv[1]
os.makedirs(out, exist_ok=True)
T = open('dune_unpacked.prg', 'rb').read()[28:]
COPY = {'INTRO.TNY': 'intro.tny', 'DUNE.TNY': 'dune.tny', 'MENU.TNY': 'menu.tny',
        'BLACKEAG.DAT': 'blackeag.tny', 'ALPHA.DAT': 'alpha.dat', 'FONTE.DAT': 'fonte.dat',
        'BLACK.DAT': 'black.dat', 'XYEAGLE.DAT': 'xyeagle.dat'}
for src, dst in COPY.items():
    shutil.copyfile(os.path.join('files', src), os.path.join(out, dst))
assert open('files/FONTE.DAT', 'rb').read() == T[0xEC40:0xEC40 + 4968]
assert open('files/XYEAGLE.DAT', 'rb').read() == T[0x10EFE:0x10EFE + 1258]


def words(off, n):
    return list(struct.unpack(f'>{n}H', T[off:off + 2 * n]))


def until0(off):
    n = 0
    while struct.unpack('>H', T[off + 2 * n:off + 2 * n + 2])[0]:
        n += 1
    return words(off, n)


def text(off):
    return list(T[off:T.index(b'\xff', off)])


def zarr(name, typ, vals, doc, per=12, fmt='0x{:04x}'):
    lines = [f'/// {doc}', f'pub const {name} = [_]{typ}{{']
    for i in range(0, len(vals), per):
        lines.append('    ' + ', '.join(fmt.format(v) for v in vals[i:i + per]) + ',')
    lines.append('};')
    return '\n'.join(lines) + '\n'


B = '{:d}'
parts = [
    '// GENERATED by prototypes/dune_gen4_re/mkassets.py from DUNE.PRG (JEK-depacked).\n'
    '// Offsets are into its TEXT segment. Do not edit: regenerate.\n',
    zarr('LETTERS', 'u16', words(0x17CC, 8 * 64),
         '$17CC: "3615 GEN4", 8 letters of 32 lines x 2 words, plane 3 only (colour 8)', 16),
    zarr('LETTER_X', 'u16', [0x08, 0x18, 0x28, 0x38, 0x58, 0x68, 0x78, 0x88],
         '$4194: each letter\'s byte column in the line (16 pixels a group of 8 bytes)', 8),
    zarr('LETTER_POS', 'u16', words(0x163C, 8), '$163C: the letters\' first index into BOUNCE', 8, B),
    zarr('BOUNCE', 'u8', words(0x166C, 176), '$166C: a letter\'s height above line 100, 176 steps', 32, B),
    zarr('RAINBOW8', 'u16', until0(0x1BF0), '$1BF0: colour 8 from line 100, one word a line (0 ends it)', 16),
    zarr('BAR', 'u16', words(0x1BCC, 16), '$1BCC: the grey bar each letter puts in colour 0', 8),
    zarr('SCROLL3', 'u16', until0(0x122A), '$122A: colour 3 under the lower border, from line 201'),
    zarr('DROP', 'u8', list(T[0x1D7E:0x1D7E + 34]), '$1D7E: the intro logo\'s line, by step 1..33', 17, B),
    zarr('MAIN_TEXT', 'u8', text(0x13DA), '$13DA: the main scroller ($FF ends it; 41 = space)', 40, B),
    zarr('MENU_RAIN15', 'u16', until0(0x10318), '$10318: colour 15 from line 11'),
    zarr('MENU_SCROLL8', 'u16', until0(0x1042C), '$1042C: colour 8 from line 150, under the low palette'),
    zarr('MENU_PAL_TOP', 'u16', words(0x10486, 16), '$10486: the menu\'s palette, set every VBL', 8),
    zarr('MENU_PAL_LOW', 'u16', words(0x10466, 16), '$10466: the palette from line 149', 8),
    zarr('MENU_TEXT', 'u8', text(0x10524), '$10524: the menu scroller ($FF wraps; 26 = space)', 40, B),
    zarr('BLACK_POS', 'u16', words(0x113E8, 5), '$113E8: each BLACK letter\'s first index into the path', 5, B),
]
open(os.path.join(out, 'tables.zig'), 'w').write('\n'.join(parts))

# F2, the HADES screen ($59CC): its big tables as binaries, the rest as Zig.
STARS, STAR_FRAMES = 75, 51
open(os.path.join(out, 'hades_stars.bin'), 'wb').write(T[0x904C:0x904C + STARS * STAR_FRAMES * 6])
open(os.path.join(out, 'hades_logo.bin'), 'wb').write(T[0x7D9E:0x86FE])
assert open('files/TETEDEAD.PRG', 'rb').read() == T[0x86FE:0x897E]
assert open('files/XYEAGLE.DAT', 'rb').read() == T[0x8A22:0x8A22 + 1258]
shutil.copyfile('files/TETEDEAD.PRG', os.path.join(out, 'tetedead.dat'))
hades = [
    '// GENERATED by prototypes/dune_gen4_re/mkassets.py from DUNE.PRG (JEK-depacked): F2,\n'
    '// the HADES screen. Offsets are into its TEXT segment. Do not edit: regenerate.\n',
    zarr('PALETTE', 'u16', words(0x789A, 16), '$789A: set at entry and every VBL', 8),
    zarr('RASTER1', 'u16', until0(0x78BA), '$78BA: colour 1 from line 201 (the scroller), one word a line'),
    zarr('WOBBLE', 'u8', list(T[0x796C:0x796C + 0x54]),
         '$796C: the logo lines\' shifts, 61 bytes rotated a VBL -- and 23 after them: from\n'
         '/// $797E on Timer B reads this memory as colour 0 words from line 201', 30, B),
    zarr('LOGO_Y', 'u16', words(0x7B6C, 0x119), '$7B6C: the logo\'s line, indices 0..$118', 20, B),
    zarr('SKULL_POS', 'u16', words(0x8A16, 5), '$8A16: each skull\'s first index into the path', 5, B),
    zarr('TEXT', 'u8', text(0xE9F4), '$E9F4: the scroller, FONTE glyphs ($FF wraps; 26 = space)', 40, B),
]
open(os.path.join(out, 'hades.zig'), 'w').write('\n'.join(hades))
print('assets ->', out)
