"""Write the CSR addresses the cycles firmware uses (fpga/cycles/board.h) from
the cycles SoC's csr.json, so no address is retyped by hand.

    uv run python tools/cycles_csr.py build/soc_cycles/csr.json build/cycles/gen/csr_addr.h

LiteX's own generated/csr.h would do, but it pulls in LiteX's libbase headers
(system.h, hw/common.h), which this firmware does not build.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# The registers the firmware touches. zm_cycles_* must stay in soc/zm_cycles.py
# COUNTERS order: board_counters() reads them as one array from the first.
NEEDED = [
    "uart_rxtx",
    "uart_txfull",
    "uart_txempty",
    "sim_finish_finish",
    "zm_cycles_cycles",
    "zm_cycles_ibus_ack",
    "zm_cycles_ibus_wait",
    "zm_cycles_dbus_rd",
    "zm_cycles_dbus_wr",
    "zm_cycles_dbus_wait",
]


def header(csr: dict[str, dict[str, int]]) -> str:
    regs = csr["csr_registers"]
    missing = [n for n in NEEDED if n not in regs]
    if missing:
        sys.exit(f"cycles_csr: the SoC has no {missing}; is it soc/cycles_sim.py's?")
    counters = [regs[n]["addr"] for n in NEEDED if n.startswith("zm_cycles_")]
    if counters != list(range(counters[0], counters[0] + 4 * len(counters), 4)):
        sys.exit(f"cycles_csr: ZMCycles counters are not one contiguous array: {counters}")
    lines = ["/* Generated by fpga/tools/cycles_csr.py from csr.json: do not edit. */"]
    lines += ["#ifndef ZM_CSR_ADDR_H", "#define ZM_CSR_ADDR_H"]
    lines += [f"#define CSR_{n.upper()}_ADDR 0x{regs[n]['addr']:08x}u" for n in NEEDED]
    return "\n".join([*lines, "#endif", ""])


def main() -> None:
    src, dst = Path(sys.argv[1]), Path(sys.argv[2])
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(header(json.loads(src.read_text())))


if __name__ == "__main__":
    main()
