"""Write the CSR addresses the cycles firmware uses (fpga/cycles/board.h) from
the cycles SoC's csr.json, so no address is retyped by hand.

    uv run python tools/cycles_csr.py build/soc_cycles/csr.json build/cycles/gen/csr_addr.h
    uv run python tools/cycles_csr.py --video build/soc_video/csr.json build/vcycles/gen/csr_addr.h

`--video`: the video sim's SoC (soc/video_sim.py), with the video pipeline's
registers, their fields and the read-back window too (fpga/cycles/vboard.h).

LiteX's own generated/csr.h would do, but it pulls in LiteX's libbase headers
(system.h, hw/common.h), which this firmware does not build.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

# The registers the firmware touches. zm_cycles_* must stay in soc/zm_cycles.py
# COUNTERS order: board_counters() reads them as one array from the first.
NEEDED = [
    "uart_rxtx",
    "uart_txfull",
    "uart_txempty",
    "sim_finish_finish",
    "zm_cycles_cycles",
    "zm_cycles_ibus_ack",
    "zm_cycles_ibus_wait",
    "zm_cycles_dbus_rd",
    "zm_cycles_dbus_wr",
    "zm_cycles_dbus_wait",
]


VIDEO = ["zmv_cmd", "zmv_status", "zmv_vbase", "zmv_fb0", "zmv_fb1", "zmv_swaps", "zmv_frame"]
VIDEO += ["zmv_comp_busy", "zmv_dma_busy"]
VIDEO += [f"main_ram_{n}" for n in ("cpu_rd", "cpu_wr", "dma_rd", "dma_wr", "both")]


def fields(prefix: str, spec: list[tuple[str, int, str]]) -> list[str]:
    """#defines of each field's shift and mask, from soc/zm_video_pipe.py's lists."""
    out, at = [], 0
    for name, width, _ in spec:
        out += [
            f"#define ZMV_{prefix}_{name.upper()}_SHIFT {at}u",
            f"#define ZMV_{prefix}_{name.upper()}_MASK 0x{(1 << width) - 1:x}u",
        ]
        at += width
    return out


def video_lines(csr: dict[str, dict[str, Any]]) -> list[str]:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from soc.zm_video_csr import CMD_FIELDS, STATUS_FIELDS

    window = csr["memories"]["zmv_window"]["base"]
    return [f"#define ZMV_WINDOW_ADDR 0x{window:08x}u", *fields("CMD", CMD_FIELDS), *fields("STATUS", STATUS_FIELDS)]


def header(csr: dict[str, dict[str, Any]], video: bool = False) -> str:
    regs = csr["csr_registers"]
    needed = NEEDED + (VIDEO if video else [])
    missing = [n for n in needed if n not in regs]
    if missing:
        sys.exit(f"cycles_csr: the SoC has no {missing}; is it soc/cycles_sim.py's?")
    counters = [regs[n]["addr"] for n in NEEDED if n.startswith("zm_cycles_")]
    if counters != list(range(counters[0], counters[0] + 4 * len(counters), 4)):
        sys.exit(f"cycles_csr: ZMCycles counters are not one contiguous array: {counters}")
    lines = ["/* Generated by fpga/tools/cycles_csr.py from csr.json: do not edit. */"]
    lines += ["#ifndef ZM_CSR_ADDR_H", "#define ZM_CSR_ADDR_H"]
    lines += [f"#define CSR_{n.upper()}_ADDR 0x{regs[n]['addr']:08x}u" for n in needed]
    if video:
        lines += video_lines(csr)
    return "\n".join([*lines, "#endif", ""])


def main() -> None:
    args = sys.argv[1:]
    video = "--video" in args
    args = [a for a in args if a != "--video"]
    src, dst = Path(args[0]), Path(args[1])
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(header(json.loads(src.read_text()), video))


if __name__ == "__main__":
    main()
