// Exports fpga/glass/src/map.zig (the PS<->PL register map) as a Verilog
// header and a Python module, and the machine's own 8x8 system font as a
// Verilog ROM initialiser for the OSD. Reflection, as memmap_export.zig does,
// so no offset is retyped.
//
//   zig run --dep glass_map -Mroot=tools/glass_export.zig -Mglass_map=glass/src/map.zig \
//       -- verilog gen/glass_map.vh | python gen/glass_map.py | font <font.raw> gen/glass_font.vh
const std = @import("std");
const map = @import("glass_map");

const Format = enum { verilog, python, font };

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    var args = init.minimal.args.iterate();
    _ = args.next();
    const format = std.meta.stringToEnum(Format, args.next() orelse return usage()) orelse return usage();
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(gpa);
    if (format == .font) {
        const raw_path = args.next() orelse return usage();
        const raw = try std.Io.Dir.cwd().readFileAlloc(init.io, raw_path, gpa, .limited(1 << 16));
        defer gpa.free(raw);
        try emitFont(gpa, &buf, raw);
    } else {
        try emitMap(gpa, &buf, format);
    }
    const out_path = args.next() orelse return usage();
    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = out_path, .data = buf.items });
}

fn usage() error{Usage} {
    std.debug.print("usage: glass_export verilog|python <out> | font <font.raw> <out>\n", .{});
    return error.Usage;
}

// localparams with no include guard: a module includes the file inside its own
// body, so each module gets its own copy (memmap.vh's guard needs an `undef
// dance for the same reason).
fn emitMap(gpa: std.mem.Allocator, buf: *std.ArrayList(u8), format: Format) !void {
    const c = if (format == .verilog) "//" else "#";
    try buf.print(gpa, "{s} GENERATED from fpga/glass/src/map.zig by fpga/tools/glass_export.zig. Do not edit.\n", .{c});
    @setEvalBranchQuota(100_000);
    inline for (@typeInfo(map).@"struct".decls) |decl| {
        const value = @field(map, decl.name);
        switch (@typeInfo(@TypeOf(value))) {
            .int, .comptime_int => {
                const v: u64 = @intCast(value);
                if (format == .verilog) {
                    try buf.print(gpa, "localparam [31:0] ZG_{s} = 32'h{X};\n", .{ decl.name, v });
                } else {
                    try buf.print(gpa, "{s} = 0x{X}\n", .{ decl.name, v });
                }
            },
            else => {},
        }
    }
}

// machine/assets/fonts/system_font_atari_1bit.raw: 256 glyphs of 8x8, one byte
// a pixel (1 = ink), glyph-major. Out: one byte a glyph row, MSB = leftmost
// pixel, at address glyph*8 + row, as an `initial` block Yosys turns into a ROM.
fn emitFont(gpa: std.mem.Allocator, buf: *std.ArrayList(u8), raw: []const u8) !void {
    if (raw.len != 256 * 64) return error.FontSize;
    try buf.appendSlice(gpa, "// GENERATED by fpga/tools/glass_export.zig from the machine's system font. Do not edit.\n");
    try buf.appendSlice(gpa, "initial begin\n");
    for (0..256 * 8) |row| {
        var byte: u8 = 0;
        for (0..8) |col| {
            if (raw[row * 8 + col] == 1) byte |= @as(u8, 0x80) >> @intCast(col);
        }
        try buf.print(gpa, "    font[{d}] = 8'h{X:0>2};\n", .{ row, byte });
    }
    try buf.appendSlice(gpa, "end\n");
}
