"""Make a "fat" .zmd: a shelf disk plus the cart's rv32 board image, for the
FPGA console's SD card (docs/FPGA_GLASS.md, "The fat disk").

    uv run python tools/zmd_fat.py DISK.zmd BOARD_IMAGE OUT.zmd

The board image (what fpga/cycles links for the cart: machine + rom + cart,
wasm2c'd and compiled for rv32) is appended block-aligned as one more FAT file,
CART.RV32 of type ZMD_TYPE_RV32, and is expected ZX0-packed already (zx0pack).
Everything else in the disk keeps its bytes: the wasm cart, its files, the
title. A v1 disk's total-blocks field grows, so its boot-sector checksum is
re-tuned to the SAME sum it had ($1234 stays bootable, $0000 stays a data
disk); a v2 boot sector holds no size and is untouched.

The browser never sees these disks: tools/mkdisks.sh still writes the shelf in
docs/, and a FAT entry of an unknown type is one it would skip anyway.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

FPGA = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(FPGA / "gen"))
import glass_map  # generated by make memmap

BLOCK = 512
FAT_ENTRY = 32
FAT_MAX = 24
NAME = b"CART.RV32"


def _layout(img: bytes) -> tuple[int, int, int]:
    """(version, offset of the file count, offset of the FAT)."""
    if img[:6] == b"ZMDISK":
        return 1, 0x2E4, 0x300
    if img[:4] == b"\0asm" and img[0x400:0x406] == b"ZMDISK":
        return 2, 0x4F4, 0x800
    raise SystemExit("zmd_fat: not a .zmd disk")


def _be_sum(buf: bytes) -> int:
    return sum((buf[2 * i] << 8) | buf[2 * i + 1] for i in range(len(buf) // 2)) & 0xFFFF


def _retune_v1(img: bytearray, total_blocks: int) -> None:
    """New total-blocks at $0A, then the checksum word back to the sum it had."""
    target = _be_sum(img[:BLOCK])
    struct.pack_into("<I", img, 0x0A, total_blocks)
    img[0x1FE:0x200] = b"\0\0"
    img[0x1FE:0x200] = ((target - _be_sum(img[:BLOCK])) & 0xFFFF).to_bytes(2, "big")
    assert _be_sum(img[:BLOCK]) == target


def fatten(disk: bytes, board: bytes) -> bytes:
    version, count_at, fat_at = _layout(disk)
    count = struct.unpack_from("<H", disk, count_at)[0]
    if count >= FAT_MAX:
        raise SystemExit(f"zmd_fat: the FAT is full ({FAT_MAX} files)")
    for i in range(count):
        if disk[fat_at + i * FAT_ENTRY + 0x18] == glass_map.ZMD_TYPE_RV32:
            raise SystemExit("zmd_fat: this disk already carries a board image")
    img = bytearray(disk)
    img.extend(b"\0" * ((-len(img)) % BLOCK))
    start = len(img)
    img.extend(board)
    img.extend(b"\0" * ((-len(img)) % BLOCK))
    entry = fat_at + count * FAT_ENTRY
    img[entry : entry + FAT_ENTRY] = (
        NAME.ljust(16, b"\0") + struct.pack("<II", start, len(board)) + bytes([glass_map.ZMD_TYPE_RV32]) + bytes(7)
    )
    struct.pack_into("<H", img, count_at, count + 1)
    if version == 1:
        _retune_v1(img, len(img) // BLOCK)
    return bytes(img)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("disk", type=Path)
    p.add_argument("board", type=Path, help="the rv32 board image, ZX0-packed")
    p.add_argument("out", type=Path)
    a = p.parse_args()
    a.out.write_bytes(fatten(a.disk.read_bytes(), a.board.read_bytes()))
    print(f"{a.out}: {a.disk.name} + {a.board.stat().st_size} B board image")


if __name__ == "__main__":
    main()
