// GENERATED by tools/private_tools/big_key1_assets.py — do not edit by hand.
//
// The B.I.G. Demo, key 1 (Colorright). Tables read out of the running demo
// (ShirazMCP, 2026-09-19); the panel and the live palette measured off the real
// screen's capture, which is exact 2x on both axes with every colour on an
// 8-level ladder at ZERO error, so ST nibbles come back exactly.

/// The band the HBL steps with `(a6)+` from $1478A, one word per scanline for
/// `d3 = $E` + 1 = FIFTEEN lines. Its width is a property of THIS table, not of
/// the two split lines — which is why the band is 15 rows wherever it is.
pub const RAMP = [15]u16{ 0x700, 0x730, 0x750, 0x770, 0x470, 0x070, 0x075, 0x077, 0x057, 0x037, 0x017, 0x307, 0x507, 0x607, 0x704 };

/// $147E4, sixteen words. Nothing in the HBL chain was known to consume it; the
/// bottom panel does, and uses these sixteen and no other colour.
pub const PANEL_PAL = [16]u16{ 0x000, 0x777, 0x666, 0x555, 0x444, 0x333, 0x222, 0x111, 0x740, 0x770, 0x470, 0x063, 0x037, 0x207, 0x507, 0x710 };

/// Pens 0..15 as they are LIVE, not as the VBL loads them: $1475C is
/// overwritten every frame and only pen 11 survives it. Recovered from the
/// capture on display lines 0..22 and 176..199 — the rows where the bitmap and
/// the still agree perfectly, which are exactly the rows no star can occupy.
/// Pens 1, 2 and 3 are the TEX cube's three faces and appear nowhere else —
/// which is why no STAR ever uses them: the generator rejects a pen <= 3.
pub const LIVE = [16]u16{ 0x000, 0x666, 0x444, 0x222, 0x232, 0x332, 0x322, 0x322, 0x322, 0x422, 0x422, 0x423, 0x413, 0x513, 0x514, 0x515 };

/// The sweep: Timer B IS the counter, and it walks 3 -> 180 -> 3 one line a
/// frame — 177 lines each way, 354 frames, about 7.1 s at 50 Hz.
pub const SWEEP_LO: i32 = 3;
pub const SWEEP_HI: i32 = 180;

/// The stars: rejection-sampled, and the three constants are visible in the
/// capture. Y rejects > $98 then adds $17; X masks to EVEN, rejects > $E7 then
/// adds $2C; the pen rejects <= 3. Measured against the bitmap: 3023 of 3023
/// stars at an even x, x in 46..274, y in 23..175, pens 4..15 near-uniform.
pub const STAR_X0: usize = 44;
pub const STAR_X1: usize = 274; // inclusive, even only
pub const STAR_Y0: usize = 23;
pub const STAR_Y1: usize = 175; // inclusive
