// GENERATED by tools/private_tools/big_key2_assets.py — do not edit by hand.
//
// The B.I.G. Demo, key 2: the 512-colour Psych-O-Screen's starting state, read
// out of the running demo (ShirazMCP, 2026-09-19) at one frozen instant, so the
// table's phase, the bitmap and the palette all belong to the same frame.
//
// The table is a FULL 16-COLOUR PALETTE PER SCANLINE for 150 scanlines, from
// $1BD00 with stride $20, consumed by the HBL at $18DAE from Timer B = 45. It
// is NOT shipped data: the demo generates it, and the generator is seeded from
// hardware entropy ($4BA, the 200 Hz clock, and $FF8206, the live beam
// position), so two runs of the real demo do not produce the same plane. What
// is reproducible is the STRUCTURE, and this file is one valid starting state.

/// The whole region the shift covers, tail included: the visible 150 lines are
/// fed from the 62 rows below them.
pub const ROWS: usize = 212;
pub const LINES: usize = 150;
pub const PENS: usize = 16;
/// Display line the table's first row lands on: Timer B = $2D = 45.
pub const FIRST_LINE: usize = 45;

/// $18F24, the VBL's base palette — what every line outside 45..194 shows.
pub const BASE = [16]u16{ 0x000, 0x007, 0x000, 0x000, 0x000, 0x000, 0x110, 0x330, 0x660, 0x000, 0x000, 0x000, 0x000, 0x000, 0x000, 0x700 };
