// GENERATED by tools/private_tools/big_key3_assets.py — do not edit by hand.
//
// The B.I.G. Demo, key 3: the raster field's own data, read out of the running
// demo (ShirazMCP, 2026-09-19) rather than transcribed from anything. The dump
// base $1B58E is pinned by the four table pointers at $1B7E6..$1B7F2, which
// land on $1B5AE / $1B628 / $1B6A2 / $1B6F4 exactly, and each gap between
// consecutive tables matches its consumer's write count (122, 122, 82 bytes =
// 61, 61, 41 words). Nothing here is inferred from a picture.
//
// PENS. 0..15 are the demo's own base palette. 16 upward is one pen per
// distinct colour-0 word in the region, so a raster band is an ordinary indexed
// fill: this machine has no intra-scanline palette write, and it does not need
// one when colour 0 is the only thing changing.
//
// REGION is the four tables CONTIGUOUS, which is how they sit in memory
// ($1B5AE..$1B746). That matters: each table's scroll shifts its words up by
// one, so a table pulls from the table that follows it.

pub const Step = struct { count: u16, reload: u16 };

pub const REGION = [204]u8{
    57, 56, 49, 48, 42, 41, 35, 30, 29, 28, 27, 26, 25, 24, 16, 67, 63, 62, 57, 56,
    49, 48, 42, 41, 35, 30, 29, 28, 27, 26, 25, 24, 16, 67, 63, 62, 57, 56, 49, 48,
    42, 41, 35, 30, 29, 28, 27, 26, 25, 24, 16, 67, 63, 62, 57, 56, 49, 48, 67, 63,
    62, 74, 73, 72, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 64, 58, 50, 43, 36,
    31, 16, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 64, 58, 50, 43, 36, 31, 16,
    78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 64, 58, 50, 43, 36, 31, 16, 78, 77,
    76, 75, 82, 81, 80, 79, 66, 65, 60, 55, 53, 51, 46, 44, 39, 37, 33, 31, 16, 83,
    82, 81, 80, 79, 83, 82, 81, 80, 79, 66, 65, 60, 55, 53, 51, 46, 44, 39, 37, 33,
    31, 16, 83, 21, 20, 19, 18, 17, 16, 61, 59, 54, 52, 47, 61, 59, 54, 52, 47, 45,
    40, 38, 34, 32, 23, 22, 21, 20, 19, 18, 17, 16, 61, 59, 54, 52, 47, 45, 40, 38,
    34, 32, 23, 22,
};

/// Where each table starts inside REGION, and how long it is.
pub const A1: usize = 0;
pub const A2: usize = 61;
pub const R1: usize = 122;
pub const R2: usize = 163;
pub const PER_LINE: usize = 61;
pub const RUN: usize = 41;

/// The four scroll SCRIPTS, each a run of (count, reload) pairs ending in a
/// negative word that rewinds to the script's own start. The table shifts up
/// one word every `reload` frames, and after `count` shifts the next pair takes
/// over — so each table scrolls on its own changing schedule.
///
/// $1B746's script is the one ShirazMCP actually READ, together with the engine
/// that walks it. The other three are real data at the addresses the other
/// three sections load ($1B778, $1B7AA, $1B7C8), and every one of them is a
/// clean $FFFF-terminated run of plausible (count, reload) pairs — but that
/// they drive a2, R1 and R2 respectively is a SHAPE ARGUMENT, not a reading.
/// Flagged here rather than in a commit message because this is where someone
/// checking it would look.
pub const S_A1 = [_]Step{ .{ .count = 4, .reload = 50 }, .{ .count = 200, .reload = 1 }, .{ .count = 50, .reload = 2 }, .{ .count = 10, .reload = 4 }, .{ .count = 30, .reload = 3 }, .{ .count = 40, .reload = 2 }, .{ .count = 50, .reload = 1 }, .{ .count = 10, .reload = 6 }, .{ .count = 50, .reload = 4 }, .{ .count = 50, .reload = 3 }, .{ .count = 100, .reload = 1 } };
pub const S_A2 = [_]Step{ .{ .count = 250, .reload = 1 }, .{ .count = 40, .reload = 2 }, .{ .count = 30, .reload = 3 }, .{ .count = 20, .reload = 4 }, .{ .count = 10, .reload = 7 }, .{ .count = 100, .reload = 1 }, .{ .count = 200, .reload = 2 }, .{ .count = 46, .reload = 3 }, .{ .count = 53, .reload = 2 }, .{ .count = 40, .reload = 2 } };
pub const S_R2 = [_]Step{ .{ .count = 30, .reload = 2 }, .{ .count = 100, .reload = 1 }, .{ .count = 100, .reload = 2 }, .{ .count = 200, .reload = 1 }, .{ .count = 50, .reload = 2 } };
pub const S_R1 = [_]Step{ .{ .count = 10, .reload = 7 }, .{ .count = 50, .reload = 2 }, .{ .count = 200, .reload = 1 }, .{ .count = 10, .reload = 10 }, .{ .count = 10, .reload = 1 }, .{ .count = 5, .reload = 20 }, .{ .count = 150, .reload = 1 } };
