// GENERATED by tools/private_tools/big_keyB_assets.py — do not edit by hand.
//
// The B.I.G. Demo, key B. Base palette and ramp read out of the running demo
// ($D39A and $C038); the layer split taken from its own screen RAM.

/// $D39A, loaded by the VBL. Pens 8..11 are all $0700 — those are the four the
/// HBL rewrites. Pens 12..15 REPEAT 4..7 exactly, which is why the glyph plane
/// shows nothing over the lit cave. Entry 0 is $0000: key B's border is static
/// black, unlike the menu's and unlike key 2's.
pub const BASE = [16]u16{ 0x000, 0x333, 0x222, 0x111, 0x445, 0x334, 0x223, 0x112, 0x700, 0x700, 0x700, 0x700, 0x445, 0x334, 0x223, 0x112 };

/// $C038, 32 words, $FFFF-terminated. Timer B = $41 = 65, so the first write
/// lands on display line 66, and Timer B is then 2 — ONE WORD EVERY TWO LINES.
/// 32 x 2 = 64 lines, display 66..129, after which the pens HOLD the last
/// word for the rest of the frame.
///
/// Verified against the capture to the scanline: every colour spans exactly two
/// display lines, the sequence is this table in order, and $0607 is still on
/// screen at lines 130..131 because that is the hold, not a 33rd entry.
pub const RAMP = [32]u16{ 0x700, 0x710, 0x720, 0x730, 0x740, 0x750, 0x760, 0x770, 0x670, 0x570, 0x470, 0x370, 0x070, 0x072, 0x073, 0x074, 0x075, 0x076, 0x077, 0x067, 0x057, 0x047, 0x037, 0x027, 0x017, 0x007, 0x107, 0x207, 0x307, 0x407, 0x507, 0x607 };

/// The glyph band, from the bitmap: plane 3 is set on exactly these rows.
pub const BAND_Y: usize = 68;
pub const BAND_H: usize = 64;
/// Timer B = $41 = 65 -> the first ramp write is on this line, two above the
/// band, so the first two ramp lines have no glyph to colour.
pub const RAMP_Y: usize = 66;

/// The font: 90 half-glyphs of 32x64, ONE BIT PER PIXEL. Byte b of the text
/// picks plane b div 30 and cell b mod 30 of a three-bank image, and a 64-px
/// character is the pair (b, b+1) in the same plane. Plane 3 is blank by
/// design, which is what makes $5A ($5A div 30 = 3) the space.
pub const HALVES: usize = 90;
pub const CELL_W: usize = 32;
pub const GH: usize = 64;
pub const CHAR_W: usize = 2 * CELL_W;
/// $5A: both halves, and the only character whose two bytes are equal.
pub const SPACE: u8 = 0x5A;
