// The B.I.G. Demo's jukebox rows, GENERATED from the table ripped out of the
// running demo's memory. Do not hand-edit: see big/list.zig for where this
// comes from, how it was verified, and what every field means.
pub const Entry = struct {
    label: []const u8, // 35 chars, printed with the 8x8 list font, VERBATIM
    song: []const u8, // "" = nothing to play
    tune: u8, // SNDH subtune, counting from 1 (= table byte 36 + 1)
};

pub const ENTRIES = [_]Entry{
    .{ .label = "----------TOP OF LIST--------------", .song = "", .tune = 0 },
    .{ .label = "                                   ", .song = "", .tune = 0 },
    .{ .label = "            ACE 2            |05'52", .song = "big/Ace_2.sndh", .tune = 1 },
    .{ .label = "       ACTION-BIKER #1       |03'09", .song = "big/Clumsy_Colin_Action_Biker.sndh", .tune = 1 },
    .{ .label = "       ACTION-BIKER #2       |01'01", .song = "big/Clumsy_Colin_Action_Biker.sndh", .tune = 2 },
    .{ .label = "       ACTION-BIKER #3       |00'11", .song = "big/Clumsy_Colin_Action_Biker.sndh", .tune = 3 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #1   |06'04", .song = "big/Aufweidersehen_Monty.sndh", .tune = 1 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #2   |00'09", .song = "big/Aufweidersehen_Monty.sndh", .tune = 2 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #3   |00'11", .song = "big/Aufweidersehen_Monty.sndh", .tune = 3 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #4   |00'05", .song = "big/Aufweidersehen_Monty.sndh", .tune = 4 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #5   |00'07", .song = "big/Aufweidersehen_Monty.sndh", .tune = 5 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #6   |00'08", .song = "big/Aufweidersehen_Monty.sndh", .tune = 6 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #7   |00'09", .song = "big/Aufweidersehen_Monty.sndh", .tune = 7 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #8   |00'08", .song = "big/Aufweidersehen_Monty.sndh", .tune = 8 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #9   |00'07", .song = "big/Aufweidersehen_Monty.sndh", .tune = 9 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #10  |00'09", .song = "big/Aufweidersehen_Monty.sndh", .tune = 10 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #11  |00'08", .song = "big/Aufweidersehen_Monty.sndh", .tune = 11 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #12  |00'07", .song = "big/Aufweidersehen_Monty.sndh", .tune = 12 },
    .{ .label = "   AUFWIEDERSEHEN MONTY #13  |00'18", .song = "big/Aufweidersehen_Monty.sndh", .tune = 13 },
    .{ .label = "      BALLOON CHALLENGE #1   |03'44", .song = "big/Balloon_Challange.sndh", .tune = 1 },
    .{ .label = "      BALLOON CHALLENGE #2   |00'07", .song = "big/Balloon_Challange.sndh", .tune = 2 },
    .{ .label = "      BATTLE OF BRITAIN      |04'12", .song = "big/Battle_Of_Britain.sndh", .tune = 1 },
    .{ .label = "      BUMP SET & SPIKE #1    |02'49", .song = "big/Bump_Set_And_Spike.sndh", .tune = 1 },
    .{ .label = "      BUMP SET & SPIKE #2    |03'10", .song = "big/Bump_Set_And_Spike.sndh", .tune = 2 },
    .{ .label = "         CHIMERA  #1         |03'38", .song = "big/Chimera.sndh", .tune = 1 },
    .{ .label = "         CHIMERA  #2         |02'02", .song = "big/Chimera.sndh", .tune = 2 },
    .{ .label = "         COMMANDO #1         |03'56", .song = "big/Commando.sndh", .tune = 1 },
    .{ .label = "         COMMANDO #2         |01'01", .song = "big/Commando.sndh", .tune = 2 },
    .{ .label = "         COMMANDO #3         |00'06", .song = "big/Commando.sndh", .tune = 3 },
    .{ .label = "          CONFUZION          |01'34", .song = "big/Confuzion.sndh", .tune = 1 },
    .{ .label = "       CRAZY COMETS #1       |04'20", .song = "big/Crazy_Comets.sndh", .tune = 1 },
    .{ .label = "       CRAZY COMETS #2       |01'06", .song = "big/Crazy_Comets.sndh", .tune = 2 },
    .{ .label = "          DELTA  #1          |01'33", .song = "big/Delta.sndh", .tune = 1 },
    .{ .label = "          DELTA  #2          |01'33", .song = "big/Delta.sndh", .tune = 2 },
    .{ .label = "          DELTA  #3          |00'04", .song = "big/Delta.sndh", .tune = 3 },
    .{ .label = "          DELTA  #4          |00'06", .song = "big/Delta.sndh", .tune = 4 },
    .{ .label = "          DELTA  #5          |00'08", .song = "big/Delta.sndh", .tune = 5 },
    .{ .label = "          DELTA  #6          |00'06", .song = "big/Delta.sndh", .tune = 6 },
    .{ .label = "          DELTA  #7          |00'06", .song = "big/Delta.sndh", .tune = 7 },
    .{ .label = "          DELTA  #8          |00'05", .song = "big/Delta.sndh", .tune = 8 },
    .{ .label = "          DELTA  #9          |00'08", .song = "big/Delta.sndh", .tune = 9 },
    .{ .label = "          DELTA  #10         |00'11", .song = "big/Delta.sndh", .tune = 10 },
    .{ .label = "        DELTA  PREVIEW       |04'11", .song = "", .tune = 0 },
    .{ .label = "          EDUCATION          |01'02", .song = "big/Education.sndh", .tune = 1 },
    .{ .label = "         FORMULA-ONE         |02'48", .song = "big/Formula_1.sndh", .tune = 1 },
    .{ .label = "        FLASH  GORDON        |05'43", .song = "big/Flash_Gordon.sndh", .tune = 1 },
    .{ .label = "      GERRY THE GERM #1      |01'32", .song = "big/Gerry_The_Germ.sndh", .tune = 1 },
    .{ .label = "      GERRY THE GERM #2      |01'47", .song = "big/Gerry_The_Germ.sndh", .tune = 2 },
    .{ .label = "      GERRY THE GERM #3      |01'43", .song = "big/Gerry_The_Germ.sndh", .tune = 3 },
    .{ .label = "      GERRY THE GERM #4      |02'11", .song = "big/Gerry_The_Germ.sndh", .tune = 4 },
    .{ .label = "      GERRY THE GERM #5      |01'43", .song = "big/Gerry_The_Germ.sndh", .tune = 5 },
    .{ .label = "      GERRY THE GERM #6      |01'08", .song = "big/Gerry_The_Germ.sndh", .tune = 6 },
    .{ .label = "      GERRY THE GERM #7      |01'47", .song = "big/Gerry_The_Germ.sndh", .tune = 7 },
    .{ .label = "       GREMLIN DEMO #1       |02'34", .song = "big/Gremlin_Music_Demo.sndh", .tune = 1 },
    .{ .label = "       GREMLIN DEMO #2       |01'28", .song = "big/Gremlin_Music_Demo.sndh", .tune = 2 },
    .{ .label = "       GREMLIN DEMO #3       |01'44", .song = "big/Gremlin_Music_Demo.sndh", .tune = 3 },
    .{ .label = "       GREMLIN DEMO #4       |02'30", .song = "big/Gremlin_Music_Demo.sndh", .tune = 4 },
    .{ .label = "       GREMLIN DEMO #5       |01'56", .song = "big/Gremlin_Music_Demo.sndh", .tune = 5 },
    .{ .label = "       GREMLIN DEMO #6       |01'17", .song = "big/Gremlin_Music_Demo.sndh", .tune = 6 },
    .{ .label = "       GREMLIN DEMO #7       |01'56", .song = "big/Gremlin_Music_Demo.sndh", .tune = 7 },
    .{ .label = "       HUMAN  RACE  #1       |02'28", .song = "big/Human_Race.sndh", .tune = 1 },
    .{ .label = "       HUMAN  RACE  #2       |01'10", .song = "big/Human_Race.sndh", .tune = 2 },
    .{ .label = "       HUMAN  RACE  #3       |01'18", .song = "big/Human_Race.sndh", .tune = 3 },
    .{ .label = "       HUMAN  RACE  #4       |02'43", .song = "big/Human_Race.sndh", .tune = 4 },
    .{ .label = "       HUMAN  RACE  #5       |02'19", .song = "big/Human_Race.sndh", .tune = 5 },
    .{ .label = "        HUNTER PATROL        |03'35", .song = "big/Hunter_Patrol.sndh", .tune = 1 },
    .{ .label = "           I, BALL           |04'56", .song = "big/I-Ball.sndh", .tune = 1 },
    .{ .label = "    INTERNATIONAL KARATE     |09'33", .song = "big/International_Karate.sndh", .tune = 1 },
    .{ .label = "   INTERNATIONAL KARATE II   |07'37", .song = "big/International_Karate_Plus.sndh", .tune = 1 },
    .{ .label = "          LABELLO            |04'51", .song = "big/Labello.sndh", .tune = 1 },
    .{ .label = "         LIGHTFORCE          |04'16", .song = "big/Lightforce.sndh", .tune = 1 },
    .{ .label = "         LOCOMOTION          |02'01", .song = "big/Locomotion.sndh", .tune = 1 },
    .{ .label = "     MASTER OF MAGIC #1      |05'21", .song = "big/Master_Of_Magic.sndh", .tune = 1 },
    .{ .label = "     MASTER OF MAGIC #2      |00'12", .song = "big/Master_Of_Magic.sndh", .tune = 2 },
    .{ .label = "     MASTER OF MAGIC #3      |00'24", .song = "big/Master_Of_Magic.sndh", .tune = 3 },
    .{ .label = "    MONTY ON THE RUN  #1     |05'50", .song = "big/Monty_On_The_Run.sndh", .tune = 1 },
    .{ .label = "    MONTY ON THE RUN  #2     |02'45", .song = "big/Monty_On_The_Run.sndh", .tune = 2 },
    .{ .label = "    MONTY ON THE RUN  #3     |00'24", .song = "big/Monty_On_The_Run.sndh", .tune = 3 },
    .{ .label = "          NEMESIS            |06'50", .song = "big/Nemesis_The_Warlock.sndh", .tune = 1 },
    .{ .label = "   ONE MAN AND HIS  DROID    |05'48", .song = "big/One_Man_and_His_Droid.sndh", .tune = 1 },
    .{ .label = " PHANTOMS OF THE ASTEROID #1 |04'16", .song = "big/Phantom_Of_The_Asteroid.sndh", .tune = 1 },
    .{ .label = " PHANTOMS OF THE ASTEROID #2 |02'19", .song = "big/Phantom_Of_The_Asteroid.sndh", .tune = 2 },
    .{ .label = " SAMANTHA-FOX STRIP-POKER #1 |01'14", .song = "big/Sam_Fox_Strip_Poker.sndh", .tune = 1 },
    .{ .label = " SAMANTHA-FOX STRIP-POKER #2 |00'06", .song = "big/Sam_Fox_Strip_Poker.sndh", .tune = 2 },
    .{ .label = " SAMANTHA-FOX STRIP-POKER #3 |00'04", .song = "big/Sam_Fox_Strip_Poker.sndh", .tune = 3 },
    .{ .label = " SAMANTHA-FOX STRIP-POKER #4 |00'04", .song = "big/Sam_Fox_Strip_Poker.sndh", .tune = 4 },
    .{ .label = " SAMANTHA-FOX STRIP-POKER #5 |00'34", .song = "big/Sam_Fox_Strip_Poker.sndh", .tune = 5 },
    .{ .label = " SAMANTHA-FOX STRIP-POKER #6 |00'02", .song = "big/Sam_Fox_Strip_Poker.sndh", .tune = 6 },
    .{ .label = "        SANXION-LOADER       |05'34", .song = "big/Sanxion_Loader.sndh", .tune = 1 },
    .{ .label = "           SANXION           |02'49", .song = "big/Sanxion_Title.sndh", .tune = 1 },
    .{ .label = "         SHOWJUMPING         |02'47", .song = "big/Harvey_Smiths_Show_Jumping.sndh", .tune = 1 },
    .{ .label = "         SMALL TITLE         |01'02", .song = "big/Small_Title.sndh", .tune = 1 },
    .{ .label = "          SPELLBOUND         |05'10", .song = "big/Spellbound.sndh", .tune = 1 },
    .{ .label = "         STARPAWS  #1        |03'06", .song = "big/Starpaws.sndh", .tune = 1 },
    .{ .label = "         STARPAWS  #2        |00'48", .song = "big/Starpaws.sndh", .tune = 2 },
    .{ .label = "         STARPAWS  #3        |00'05", .song = "big/Starpaws.sndh", .tune = 3 },
    .{ .label = "         STRONGMAN #1        |00'16", .song = "big/Geoff_Capes_Strongman.sndh", .tune = 1 },
    .{ .label = "         STRONGMAN #2        |00'11", .song = "big/Geoff_Capes_Strongman.sndh", .tune = 2 },
    .{ .label = "         STRONGMAN #3        |00'16", .song = "big/Geoff_Capes_Strongman.sndh", .tune = 3 },
    .{ .label = "         STRONGMAN #4        |00'10", .song = "big/Geoff_Capes_Strongman.sndh", .tune = 4 },
    .{ .label = "         STRONGMAN #5        |00'12", .song = "big/Geoff_Capes_Strongman.sndh", .tune = 5 },
    .{ .label = "         STRONGMAN #6        |00'11", .song = "big/Geoff_Capes_Strongman.sndh", .tune = 6 },
    .{ .label = "           THALAMUS          |02'18", .song = "", .tune = 0 },
    .{ .label = "        THE LAST V8 #1       |02'23", .song = "big/The_Last_V8.sndh", .tune = 1 },
    .{ .label = "        THE LAST V8 #2       |00'13", .song = "", .tune = 0 },
    .{ .label = "        THE LAST V8 #3       |00'09", .song = "", .tune = 0 },
    .{ .label = "       THING ON A SPRING     |03'42", .song = "big/Thing_On_A_Spring.sndh", .tune = 1 },
    .{ .label = "            THRUST           |05'41", .song = "big/Thrust.sndh", .tune = 1 },
    .{ .label = "   (MAKE L.O.V.E. NOT) W.A.R.|08'32", .song = "big/Make_Love_Not_W_A_R.sndh", .tune = 1 },
    .{ .label = "            WARHAWK          |03'30", .song = "big/Warhawk.sndh", .tune = 1 },
    .{ .label = "            WIZ  #1          |05'31", .song = "big/Wiz.sndh", .tune = 1 },
    .{ .label = "            WIZ  #2          |03'08", .song = "big/Wiz.sndh", .tune = 2 },
    .{ .label = "            WIZ  #3          |00'07", .song = "big/Wiz.sndh", .tune = 3 },
    .{ .label = "            ZOOLOOK          |04'53", .song = "big/Zoolook.sndh", .tune = 1 },
    .{ .label = "             ZOIDS           |05'07", .song = "big/Zoids.sndh", .tune = 1 },
    .{ .label = "  -=THE DIGITAL DEPARTMENT=-       ", .song = "", .tune = 0 },
    .{ .label = "                                   ", .song = "", .tune = 0 },
    .{ .label = "---------BOTTOM OF LIST------------", .song = "", .tune = 0 },
};
