// The disk's own files, as DUNE.PRG reads them, and the tables out of the
// program itself (tables.zig, generated by prototypes/dune_gen4_re/mkassets.py).
const DIR = "../../assets/screens/dune_gen4/";

pub const T = @import("../../assets/screens/dune_gen4/tables.zig");

pub const INTRO_TNY = @embedFile(DIR ++ "intro.tny"); // the DUNE logo, intro + main part
pub const DUNE_TNY = @embedFile(DIR ++ "dune.tny"); // the title picture
pub const MENU_TNY = @embedFile(DIR ++ "menu.tny");
pub const SOUND_TNY = @embedFile(DIR ++ "sound.tny"); // F3, "520 SOUNDTRACKER"
/// On the disk as BLACKEAG.DAT; F1 asks for "A:blackeag.tny" (see black.zig).
pub const BLACKEAG_TNY = @embedFile(DIR ++ "blackeag.tny");

/// ALPHA.DAT: the main scroller's 41 glyphs, 32x32 in two bitplanes. A line is
/// four words: plane 0 and plane 1 of pixels 0..15, then of 16..31.
pub const ALPHA = @embedFile(DIR ++ "alpha.dat");
pub const ALPHA_GLYPHS = 41;
/// FONTE.DAT (the copy inside DUNE.PRG at $EC40 is byte-identical): the menu
/// scroller's glyphs, 32x27 in one bitplane, a long a line.
pub const FONTE = @embedFile(DIR ++ "fonte.dat");
pub const FONTE_GLYPHS = 46;
/// BLACK.DAT: five 32x32 letters in four bitplanes (16 bytes a line).
pub const BLACK = @embedFile(DIR ++ "black.dat");
/// XYEAGLE.DAT (= DUNE.PRG $10EFE and $8A22): the path of F1's BLACK letters and
/// of F2's skulls, (x << 8 | y) words.
pub const XYEAGLE = @embedFile(DIR ++ "xyeagle.dat");

/// F2, the HADES screen: its tables (hades.zig, generated) and TETEDEAD.PRG
/// (= DUNE.PRG $86FE), the skull: 32 lines of two (mask + 4 planes) groups.
pub const HADES = @import("../../assets/screens/dune_gen4/hades.zig");
pub const TETEDEAD = @embedFile(DIR ++ "tetedead.dat");

comptime {
    if (ALPHA.len != ALPHA_GLYPHS * 256) @compileError("ALPHA.DAT is 41 glyphs of 256 bytes");
    if (FONTE.len < FONTE_GLYPHS * 108) @compileError("FONTE.DAT is 46 glyphs of 108 bytes");
    if (BLACK.len != 5 * 32 * 16) @compileError("BLACK.DAT is 5 letters of 512 bytes");
    if (XYEAGLE.len < 2 * 629) @compileError("XYEAGLE.DAT is 629 path words");
    if (T.LETTERS.len != 8 * 64) @compileError("8 letters of 32 lines x 2 words");
    if (T.BOUNCE.len != 176) @compileError("BOUNCE runs 0..$AF");
}
