// --------------------------------------------------------------------------
// F3 against the ORIGINAL code: its memory after N VBLs (VBL $1888E + the
// main loop's body $1810A..$180FA, no key) on the Musashi oracle, as CRC32s
// of [$14000, $7FC00) without the part's stack page ($28000..$28400) and of
// the two screens ($60000..$7FC00). The Timer B chain and the music are not run there
// (they only write colour registers and the YM). Generated by
//   m68run f3_init.bin ... loop:N:vbl:1888e:exec:1810a:180fa
// (prototypes/snyd90_re/mk_parts.py makes f3_init's asset). Run through
// apps/zig/scene_tests.zig.
// --------------------------------------------------------------------------
const std = @import("std");
const st = @import("../swedish_newyear/st.zig");
const f3 = @import("f3.zig");

const IMAGE = @embedFile("../../assets/screens/snyd_90/f3.raw");

var mem: [f3.TOP - f3.BASE]u8 = undefined;

const Expect = struct { vbl: u32, mem: u32, screens: u32 };
const EXPECT = [_]Expect{
    .{ .vbl = 1, .mem = 0xb298df68, .screens = 0x0b1033a8 },
    .{ .vbl = 5, .mem = 0x5eda7baf, .screens = 0x551167e2 },
    .{ .vbl = 300, .mem = 0x697f97ac, .screens = 0x36d8499e },
};

/// The oracle's own stack sits at $7FDxx: past every line the part shows.
const TOP: u32 = 0x7FC00;

fn kept(r: *const st.Ram) u32 {
    var h = std.hash.Crc32.init();
    h.update(r.bytes(0x14000, 0x28000 - 0x14000));
    h.update(r.bytes(0x28400, TOP - 0x28400));
    return h.final();
}

test "F3 matches the original code's memory after 1, 5 and 300 VBLs" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f3.BASE, .m = &mem };
    f3.enter();
    var done: u32 = 0;
    for (EXPECT) |e| {
        while (done < e.vbl) : (done += 1) _ = f3.vbl(&r);
        try std.testing.expectEqual(e.screens, std.hash.Crc32.hash(r.bytes(0x60000, TOP - 0x60000)));
        try std.testing.expectEqual(e.mem, kept(&r));
    }
}

test "F3's preset key reloads the curve and redraws the panel in its own VBL" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f3.BASE, .m = &mem };
    f3.enter();
    f3.key(0xE003); // F3: preset 3 (SX $0038 ...)
    for (0..3) |_| _ = f3.vbl(&r); // the first key tick ($1AAA6 starts at 3)
    try std.testing.expectEqual(@as(u16, 0x38), r.w(0x1AAC6));
    const before = r.w(0x1CA64);
    _ = f3.vbl(&r); // the redraw-all VBL: no main loop, no flash count
    try std.testing.expectEqual(before, r.w(0x1CA64));
}

test "F3's rasters: the horizon from line 139, the water's colours from 188" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f3.BASE, .m = &mem };
    var lines: [f3.LINES][16]u16 = undefined;
    f3.rasters(&r, &lines);
    try std.testing.expectEqual(@as(u16, 0), lines[138][0]);
    try std.testing.expectEqual(@as(u16, 3), lines[141][0]);
    try std.testing.expectEqual(@as(u16, 0x27), lines[188][13]);
    try std.testing.expect(lines[0][1] != lines[188][1]);
}
