// --------------------------------------------------------------------------
// F4 against the ORIGINAL code, iteration-locked: its memory ([$7000,
// $7FC00) without the music $17FC0..$1AEDC -- the SNDH's --, the VBL flag
// $F3EA and the stack page below $60000) after N passes of VBL $F2BE + the
// main loop's body $F1B8..$F274 on the Musashi oracle. (On the ST a pass
// sometimes overruns its frame; the port, like this oracle run, does one a
// VBL.) Generated by prototypes/snyd90_re/parts_expect.py f4. Run through
// apps/zig/scene_tests.zig.
// --------------------------------------------------------------------------
const std = @import("std");
const st = @import("../swedish_newyear/st.zig");
const f4 = @import("f4.zig");

const IMAGE = @embedFile("../../assets/screens/snyd_90/f4.raw");

var mem: [f4.TOP - f4.BASE]u8 = undefined;

const Expect = struct { vbl: u32, mem: u32 };
const EXPECT = [_]Expect{
    .{ .vbl = 1, .mem = 0xed1f1498 },
    .{ .vbl = 5, .mem = 0x80a2c0ab },
    .{ .vbl = 300, .mem = 0x590a57e0 },
    .{ .vbl = 1200, .mem = 0x7205627d },
};
const HOLES = [_][2]u32{ .{ 0xF3EA, 0xF3EC }, .{ 0x17FC0, 0x1AEDC }, .{ 0x5F000, 0x60000 } };

fn kept(r: *const st.Ram) u32 {
    var h = std.hash.Crc32.init();
    var a: u32 = f4.BASE;
    const zeros = [_]u8{0} ** 0x1000;
    for (HOLES) |hole| {
        h.update(r.bytes(a, hole[0] - a));
        var n = hole[1] - hole[0];
        while (n > 0) : (n -= @min(n, zeros.len)) h.update(zeros[0..@min(n, zeros.len)]);
        a = hole[1];
    }
    h.update(r.bytes(a, 0x7FC00 - a));
    return h.final();
}

test "F4 matches the original code's memory after 1, 5, 300 and 1200 passes" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f4.BASE, .m = &mem };
    var done: u32 = 0;
    for (EXPECT) |e| {
        while (done < e.vbl) : (done += 1) _ = f4.vbl(&r);
        try std.testing.expectEqual(e.mem, kept(&r));
    }
}

test "F4's screens alternate and its scroller's colours start at line 183" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f4.BASE, .m = &mem };
    const a = f4.vbl(&r);
    const b = f4.vbl(&r);
    try std.testing.expect(a != b);
    try std.testing.expectEqual(@as(u16, 0x700), f4.colours(&r, 182)[4]);
    try std.testing.expectEqual(@as(u16, 0x707), f4.colours(&r, 183)[4]);
}
