// --------------------------------------------------------------------------
// F5 against the ORIGINAL code: its memory ([$C000, $7FC00): past it lies the
// oracle's own stack) after N frames of the original on the Musashi oracle --
// VBL $17D42, the main loop's body $17EDC..$17ED2, then a call of $15A68, the
// fullscreen routine's half that writes the texture and the letter column
// (its border switches only touch the oracle's register file). Generated by
// prototypes/snyd90_re/parts_expect.py f5. Run through apps/zig/scene_tests.zig.
// --------------------------------------------------------------------------
const std = @import("std");
const st = @import("../swedish_newyear/st.zig");
const f5 = @import("f5.zig");

const IMAGE = @embedFile("../../assets/screens/snyd_90/f5.raw");

var mem: [f5.TOP - f5.BASE]u8 = undefined;

const Expect = struct { vbl: u32, mem: u32 };
const EXPECT = [_]Expect{
    .{ .vbl = 1, .mem = 0x435e1929 },
    .{ .vbl = 5, .mem = 0xc68b751b },
    .{ .vbl = 300, .mem = 0xef14411e },
    .{ .vbl = 1200, .mem = 0x81834350 },
};

test "F5 matches the original code's memory after 1, 5, 300 and 1200 frames" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f5.BASE, .m = &mem };
    f5.enter(&r);
    var done: u32 = 0;
    for (EXPECT) |e| {
        while (done < e.vbl) : (done += 1) _ = f5.vbl(&r);
        try std.testing.expectEqual(e.mem, std.hash.Crc32.hash(r.bytes(f5.BASE, 0x7FC00 - f5.BASE)));
    }
}

test "F5 scrolls: the picture's start moves 8 bytes every other frame" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f5.BASE, .m = &mem };
    f5.enter(&r);
    const a = f5.vbl(&r);
    const b = f5.vbl(&r);
    const c = f5.vbl(&r);
    try std.testing.expect(a != b); // the screens swap every frame
    try std.testing.expectEqual(@as(u32, 8), c - a);
}
