// --------------------------------------------------------------------------
// F6 against the ORIGINAL code: its memory ([$C000, $7FC00) without the
// music's replay and state, $E50E..$ED08 -- the SNDH's --, and Timer B's
// raster pointer $127FA) after N VBLs on the Musashi oracle: VBL $127FE each
// one, the main loop's body $129FE..$12A3C every second. Generated by
// prototypes/snyd90_re/parts_expect.py f6. Run through apps/zig/scene_tests.zig.
// --------------------------------------------------------------------------
const std = @import("std");
const st = @import("../swedish_newyear/st.zig");
const f6 = @import("f6.zig");

const IMAGE = @embedFile("../../assets/screens/snyd_90/f6.raw");

var mem: [f6.TOP - f6.BASE]u8 = undefined;

const Expect = struct { vbl: u32, mem: u32 };
const EXPECT = [_]Expect{
    .{ .vbl = 1, .mem = 0xf0be16a4 },
    .{ .vbl = 5, .mem = 0x38395e68 },
    .{ .vbl = 300, .mem = 0x89c3f310 },
    .{ .vbl = 1200, .mem = 0x56070aa0 },
};
const HOLES = [_][2]u32{ .{ 0xE50E, 0xED08 }, .{ 0x127FA, 0x127FE } };

fn kept(r: *const st.Ram) u32 {
    var h = std.hash.Crc32.init();
    var a: u32 = f6.BASE;
    const zeros = [_]u8{0} ** 0x1000;
    for (HOLES) |hole| {
        h.update(r.bytes(a, hole[0] - a));
        var n = hole[1] - hole[0];
        while (n > 0) : (n -= @min(n, zeros.len)) h.update(zeros[0..@min(n, zeros.len)]);
        a = hole[1];
    }
    h.update(r.bytes(a, 0x7FC00 - a));
    return h.final();
}

test "F6 matches the original code's memory after 1, 5, 300 and 1200 VBLs" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f6.BASE, .m = &mem };
    f6.enter(&r);
    var done: u32 = 0;
    for (EXPECT) |e| {
        while (done < e.vbl) : (done += 1) _ = f6.vbl(&r);
        try std.testing.expectEqual(e.mem, kept(&r));
    }
}

test "F6 runs its main loop every second VBL" {
    @memcpy(&mem, IMAGE);
    const r = st.Ram{ .base = f6.BASE, .m = &mem };
    f6.enter(&r);
    const a = f6.vbl(&r); // the counter was 1: a pass, a new screen
    const b = f6.vbl(&r); // no pass
    const c = f6.vbl(&r); // a pass
    try std.testing.expectEqual(a, b);
    try std.testing.expect(c != b);
}
