// The scrolltext, verbatim from screen.js:174 (4086 characters, looped).
// It holds ONE tab, after "THIS INTRO IS FINISHED...": CODEF draws it as tile
// 9-32 = -23, which drawPart rejects, so that 32-pixel cell of the scroller is
// left unpainted. It is kept, and the port leaves the same hole (see draw.zig).
pub const TEXT: []const u8 =
    "      YO, SHITY-FUCKY-LAMEEUUUUURS !!!  AFTER HARD LABOUR, THE MEGAMIGHTY CAREBEARS AND " ++
    "THE FAMOUS REPLICANTS ARE PROUD TO PRESENT    - WEIRD DREAM -   CRACKED BY RATBOY.  " ++
    "THIS INTRO WAS CODED BY NICK, JAS AND AN THE MOTHERFUCKIN COOL AT THE FIRST MEETING TCB " ++
    "- REPLICANTS...    OK, NOW ALL THE MEMBERS OF THE WILL WRITE A PART OF THIS " ++
    "SCROLLTEXT...          HEY, IT'S RATBOY ON THE KEYBOARD, I DON'T KNOW WHAT TO WRITE AND " ++
    "I HATE WRITING SCROLLTEXT.  I'LL TELL YOU MORE DETAILS ABOUT THIS MEETING. TCB ARRIVED " ++
    "FIVE DAYS AGO. SO, THEY DECIDED TO CODE THIS FANTASTIC INTRO. AFTER 25 LITRES OF COKE, " ++
    "1 MONOPOLY PLAY, 1 BOTTLE OF WHISKY, 20 BIG TOM, SOME PING-PONG MATCHES (OK, JAS !!  " ++
    "YOU'RE BETTER THAN ME, BUT THE REVENGE OF RATBOY WILL BE TERRIBLE !), THIS INTRO IS " ++
    "FINISHED...\tOKEY, ENOUGH OF RATBOY, I (NICK) WILL TRY TO WRITE SOMETHING....    " ++
    "WELL....   EHHH...       WHAT DID YOU THINK ABOUT OUR CUDDLY DEMOS?  DIDN'T WORK?  " ++
    "WELL, WE'RE NOT INTERRESTED!  STOP COMPLAINING,  NOW EVERYTHING WORKS, BUT WE ONLY HAVE " ++
    "ONE TYPE OF COMPUTER IN SWEDEN, SO WE COULDN'T TEST IT ON ALL SHIFTERS...      YHEAAAA " ++
    "IT'S  -AN COOL- AND -SNAKE- AN COOL SMELLS A LOT OF SHIT AND SNAKE MAKES SMELLY NOISES. " ++
    "WHAT'S AN COOL AND SNAKE ?  WE ARE THE TWO CRAZY GUYS IN THE TWO CREWS. AFTER HAVING " ++
    "BEEN IN ZAE'S DIRTY HOTEL IN MARSEILLE WE ARE NOW AT THE REPLICANTS HQ (AN COOL'S FEET " ++
    "STILL SMELL LIKE AN OLD AND ROTTEN CHEESE). THIS IS AN COOL ON THE KEYBOARD.... AND I " ++
    "WILL TELL YOU A STORY.....  LAST NIGHT I WAS ASLEEP AND SUDDENLY I HEARD A NOISE, BUT " ++
    "IT WAS NOT AN ORDINARY NOISE IT WAS A SMELLY NOISE. I TRIED TO PUT MY PILLOW OVER MY " ++
    "HEAD BUT THAT WAS NO USE COZ THE SOUND WAS TO LOUD. THEN I HAD TO FIND OUT WHERE THE " ++
    "SOUND CAME FROM. I SEARCHED FOR DAYS AND NIGHTS.   SUDDENLY I FOUND IT!!!!!     IT CAME " ++
    "FROM 2 LITTLE MEN CALLED            -SNAKE AND JAS (THE ZOZO)-. AND THAT'S THE END OF " ++
    "THIS STORY. (SNAKE) HAHAH IT'S VERY FUNNY!!!!!!!!     PHEW!!! THE AN COOL PART IS OVER " ++
    "AND JAS STARTS WRITING. HAVE YOU STOPPED LAUGHING NOW, I KNOW AN COOL'S JOKE WAS VERY " ++
    "FUNNY, HE HAS SUCH AN IMAGINATION, THE PUNCHLINE WAS STUNNING. DON'T YOU THINK AN COOL " ++
    "IS A GREAT COMEDIAN. LET'S CHANGE SUBJECT....  I DON'T THINK THAT ANYONE HAS TOLD YOU " ++
    "THAT WE (THE CAREBEARS (LES BISOUNOURS)), ARE ON AN EUROTOUR. WE'VE BEEN OUT FOR TWO " ++
    "WEEKS NOW AND WE HAVE MET THE FOLLOWING (IN CHRONOLOGICAL ORDER):  TEX (WE MET 6719, " ++
    "ES, MAD MAX OF TEX, FOXX, AND GIGABYTE CREW), FASHION (THE GREAT), AND ZAE (AND THE " ++
    "REPLICANTS). BYE FROM JAS...........             NOW RATBOY AND SNAKE TAKE THE KEYBOARD " ++
    "FROM ZOZO (EXCUSE ME JAS !!) TO WRITE THE GREETINGS (AND THE FUCKING GREETINGS OF " ++
    "COURSE !!)  GIGA ULTRA SPECIAL GREET TO ALL OTHER MEMBERS OF THE UNION (THE WORLD " ++
    "NUMBER ONE). NORMAL GREETINGS TO:  THE MEDWAY BOYS, MCA ( HELLO HARRIE! ), A-HA, BIG " ++
    "FOUR, ALPHA FLIGHT, AUTOMATION ( HELLO WAS AND JEK ), REVOLUTION, OMEGA, SYNC, PHALANX, " ++
    "2 LIFE CREW, FASHION, NO CREW, DCS (ESPECIALLY R-ZAUGG), THE BROD, DMA, THG ( HI FILON " ++
    "& MAD GUS ), TSB, ZAE( HAHAHAAHA TOI PAS DORMIR ), STCS ( HI ENFOIRE DE JEAN MARC ), " ++
    "JOHN FROM GREECE AND ALL WE HAVE FORGOTTEN.....      YEEEEEEAAAHHHH, NOW HERE ARE THE " ++
    "FUCKING GREETINGS (IF YOU HAVEN'T FIND YOUR NAME IN THE GREETINGS PERHAPS ARE YOU IN " ++
    "THE FUCKING GREETINGS !!)....              4            3          2           8 " ++
    "(SHIT), SORRY I DECOUNT AGAIN....        4         3        2       1        0    AT " ++
    "FIRST WE WANT TO FUCK THE BEST LAMERS IN THE WORLD THE.. THE O.. THE OVER... THE " ++
    "OVERL... LAMERS OR LANDERS.       OK, I FORGET IT'S NOW ALLIANCE (A BUNCH OF LAMERS " ++
    "HAHAHAHA FUCK YOU)...    OK, IT'S RATBOY ON THE KEYBOARD.   HEY ! MOTHERSUCKERS, STOP " ++
    "TO SAY THAT I AND DCS WE SELL CRACKING SOFTWARES, STOP TO SAY THAT IF WE DON'T STOP TO " ++
    "FUCK YOU, YOU'LL GIVE OUR NAMES TO THE POLICE, STOP TO USE UNION DEMO ROUTS IN YOUR " ++
    "SHITY INTROS....   FUCK TO DAVID THE BIG FAT PIG...       WE WANT TO SEND A PARTICULARY " ++
    "FUCK TO DANY B. AS LE NABOT NOIR...              HERE IT'S THE END OF THIS " ++
    "SCROLLTEXT...                19-07-89    (C) TCB-REPLICANTS 1989                      ";
