// The two scrolltexts, verbatim from screen.js (var text, var text_dna).

/// The 8x6 spread scroller's text (639 characters).
pub const scroll =
    "YO, SUCKERS!!!  THIS IS THE SPREADPOINT DEMO!   ALL CODING WAS DONE BY THE C" ++
    "AREBEARS,  ALL GRAPHIXX WAS DESIGNED BY THE CAREBEARS AND THE MUZEXX WAS ALS" ++
    "O 'EINGEPLUPPED' BY THE CAREBEARS!  WE SAW THE ORIGINAL SPREADPOINT DEMO, BY" ++
    " SPREADPOINT, ON THE NO-CREW-COPY-PARTY.  ON THE TRAIN HOME, WE DISCUSSED HO" ++
    "W TO CONVERT IT TO THE ST.  WE DECIDED TO USE THIS DIGISHIT-ROUT, EVEN THOUG" ++
    "H IT TAKES SOME PROCESSOR TIME. ON AN ST, DIGISOUND RESULTS IN LESS GRAPHICA" ++
    "L MOVEMENT, BUT WE THINK THERE'S ENOUGH MOVEMENT ON THIS SCREEN, DON'T YOU? " ++
    "(DON'T ANSWER IF YOU DON'T!) YOUR EYES ARE PROBABLY STARTING TO ACHE, SO LET" ++
    "'S WRAP. THE UNION RULES.      ";

/// The DNA scroller's text (1583 characters).
pub const dna =
    "HELLO, EVERYBODY!!!  THIS IS THE SPREADPOINT DEMO, CODED BY THE CAREBEARS.  " ++
    "THE MUZEXX WAS ALSO DONE BY TCB, AND SO WAS THE GRAPHIXX (THAT'S WHY IT LOOK" ++
    "S AND SOUNDS LIKE IT DOES).  EVERYBODY COMPLAINS ABOUT THE LOUSY DIGI-SOUND-" ++
    "TUNE.  AN COOL SAYS THAT THE INSTRUMENTS SOUND TERRIBLE AND EVERYTHING IS AB" ++
    "OUT 1 KILOMETER OFF KEY.  WE AGREE THAT IT ISN'T AS GOOD AS THE ORIGINAL TUN" ++
    "E BY DEPECHE MODE - YES, IT'S SUPPOSED TO SOUND LIKE \"MASTER AND SERVANT\".  " ++
    "THERE'S NOTHING WRONG WITH OUR DIGI-SHIT ROUT, THOUGH, IT'S JUST THAT WE ONL" ++
    "Y HAD ABOUT 5 MINUTES TO SAMPLE ALL THE SOUNDS FOR THE TUNE AND WE KNOW NOTH" ++
    "ING ABOUT THOSE FUNNY-LOOKING BLACK THINGS WITH TAILS.   WE WILL HAVE A MUCH" ++
    " BETTER TUNE IN OUR NEXT DIGI-SOUND-DEMO (PERHAPS IN OUR COPY-PARTY-DEMO).  " ++
    "        YOU MIGHT WODNER WHY WE CALL IT THE SPREADPOINT DEMO.  WE'LL, WE GOT" ++
    " AN AMIGA-DEMO ON THE NO-CREW-COPY-PARTY.  IT WAS CODED BY SPREADPOINT, AN A" ++
    "MIGA-CREW.  WE THOUGHT IT WAS SO GOOD THAT WE DECIDED TO CONVERT IT TO THE S" ++
    "T.  AS YOU CAN HEAR, WE USED OUR LATEST DIGI-SHIT-ROUT.  IF WE HADN'T USED I" ++
    "T, WE WOULD HAVE BEEN ABLE TO CONVERT IT ALMOST PERFECTLY, BUT SINCE DIGI-SO" ++
    "UND TAKES A LOT OF PROCESSOR-TIME ON THE ST, WE HAD TO MAKE A SIMPLER SCROLL" ++
    "ER AND A SMALLER LOGO.    CONGRATULATIONS, YOU HAVE MANAGED TO READ ALMOST T" ++
    "HE WHOLE SCROLLTEXT, EVEN THOUGH IT'S TOTALLY ILLEGIBLE.   THEREFORE, WE WIL" ++
    "L GIVE YOU A KEYWORD TO TYPE IN THE MAIN MENU FOR A SPECIAL BONUS.  THE WORD" ++
    " IS: HUBBAGNURFGNURFTJOLAHOPPSONHEJSANBLIPPBLAPPBLOPPMASTERFAG, OR WAS IT TH" ++
    "E OTHER WAY AROUND?        LET'S WRAP.......                   ";
