// Generated by tools/private_tools/ulm_dsots_assets.py from the remake's
// data/DSOTS.tmx (Tiled, 700x40 tiles of 32x32) -- do not hand-edit.
// Coordinates are the ORIGINAL 768-wide map pixels; the scene halves on draw.

pub const COLS: usize = 700;
pub const ROWS: usize = 40; // realheight = ROWS * TILE
pub const DATA_ROWS: usize = 28; // rows 28..39 hold no tile in any layer
pub const TILE: u16 = 32;
pub const SPAWN_X: f64 = 1152; // the MainEntity object's x, y (Tiled)
pub const SPAWN_Y: f64 = 832;

/// The TMX "Doors" object group, in file order.
pub const DoorRect = struct { x: f64, y: f64, w: f64, h: f64, demo_name: []const u8 };
pub const DOORS = [_]DoorRect{
    .{ .x = 1120, .y = 288, .w = 96, .h = 96, .demo_name = "demo1" },
};
