// Generated by tools/union_intro_assets.py from assets/oldies/UnionDemoCracktro/intro/gfx/efmain_intro/back_layer*.png — do not hand-edit.
//
// STRIP_DIMS[i]   = .{ width, height } of back_layer{i}.raw (half-scale).
// STRIP_RANGE[i]  = .{ min, max } inclusive palette index owned exclusively
//                   by strip i in placement.pal (no cross-strip color reuse,
//                   so a FADE strip's range can be alpha-scaled in isolation).

pub const STRIP_DIMS = [17][2]u16{ .{ 384, 13 }, .{ 384, 19 }, .{ 384, 16 }, .{ 384, 16 }, .{ 384, 16 }, .{ 384, 16 }, .{ 384, 16 }, .{ 384, 30 }, .{ 384, 64 }, .{ 384, 32 }, .{ 384, 16 }, .{ 384, 16 }, .{ 384, 64 }, .{ 384, 16 }, .{ 384, 16 }, .{ 384, 16 }, .{ 224, 28 } };
pub const STRIP_RANGE = [17][2]u8{ .{ 1, 2 }, .{ 3, 4 }, .{ 5, 6 }, .{ 7, 8 }, .{ 9, 10 }, .{ 11, 12 }, .{ 13, 14 }, .{ 15, 15 }, .{ 16, 32 }, .{ 33, 48 }, .{ 49, 50 }, .{ 51, 52 }, .{ 53, 53 }, .{ 54, 57 }, .{ 58, 61 }, .{ 62, 65 }, .{ 66, 72 } };
