#!/usr/bin/env python3
"""Assets for the C port of CODEF screen 34 -> apps/c/assets/screens/screen34/data.h

    python3 tools/c34_assets.py

C has no @embedFile, so unlike a Zig scene this emits a HEADER: the images
become static byte arrays compiled into the cart. Source PNGs come from
prototypes/codef/34/assets/ (tools/fetch_codef.py 34).

One shared 256-colour palette across all three images, because the port draws
everything into ONE overscan plane — a plane has one palette, and plane count is
the host's per-frame cost. Index 0 is transparent/black.

Halved to ST space (the CODEF canvas is 640x480 = 320x240 doubled):
    flag   10 frames of 149x107   (298x214 each in CODEF space)
    logo   301x66                 (602x132)
    font   60 glyphs of 32x32     (64x64, first char 32)
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image

SRC = Path("prototypes/codef/34/assets")
OUT = Path("apps/c/assets/screens/screen34/data.h")

FLAG_W, FLAG_H, FLAG_FRAMES = 149, 107, 10
GLYPH, FIRST_CHAR, NB_GLYPHS = 32, 32, 60


class Palette:
    """Shared palette; index 0 is reserved transparent."""

    def __init__(self) -> None:
        self.colors: list[tuple[int, int, int, int]] = [(0, 0, 0, 0)]
        self.lookup: dict[tuple[int, int, int], int] = {}

    def index(self, rgb: tuple[int, int, int]) -> int:
        if rgb not in self.lookup:
            if len(self.colors) >= 256:
                raise SystemExit("palette overflow: more than 256 colours across the three images")
            self.lookup[rgb] = len(self.colors)
            self.colors.append((*rgb, 255))
        return self.lookup[rgb]


def index_image(im: Image.Image, pal: Palette, transparent_black: bool) -> list[int]:
    """RGBA image -> palette indices, alpha 0 (and optionally pure black) -> 0."""
    im = im.convert("RGBA")
    px = im.load()
    out = []
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if a == 0 or (transparent_black and r == 0 and g == 0 and b == 0):
                out.append(0)
            else:
                out.append(pal.index((r, g, b)))
    return out


def carray(name: str, data: list[int], per_line: int = 32) -> str:
    body = []
    for i in range(0, len(data), per_line):
        body.append("".join(f"{v}," for v in data[i:i + per_line]))
    return f"static const unsigned char {name}[{len(data)}] = {{\n" + "\n".join(body) + "\n};\n"


def main() -> None:
    if not SRC.is_dir():
        raise SystemExit(f"missing {SRC} — run: python3 tools/fetch_codef.py 34")
    pal = Palette()

    # NEAREST throughout: these are pixel-doubled originals, so halving is exact
    # and a smooth resample would invent colours that each claim a palette entry.
    flag_src = Image.open(SRC / "flag.png").resize((FLAG_W, FLAG_H * FLAG_FRAMES), Image.NEAREST)
    flag = index_image(flag_src, pal, transparent_black=True)

    logo_src = Image.open(SRC / "logo.png")
    logo_w, logo_h = logo_src.width // 2, logo_src.height // 2
    logo = index_image(logo_src.resize((logo_w, logo_h), Image.NEAREST), pal, transparent_black=True)

    # The font sheet is a 10x6 grid of 64x64 glyphs; re-lay it as one column of
    # 32x32 glyphs in character order so the scroller can index it linearly.
    fsrc = Image.open(SRC / "font.png")
    sheet = Image.new("RGBA", (GLYPH, GLYPH * NB_GLYPHS))
    for g in range(NB_GLYPHS):
        gx, gy = (g % 10) * 64, (g // 10) * 64
        cell = fsrc.crop((gx, gy, gx + 64, gy + 64)).resize((GLYPH, GLYPH), Image.NEAREST)
        sheet.paste(cell, (0, g * GLYPH))
    font = index_image(sheet, pal, transparent_black=True)

    palette_bytes: list[int] = []
    for r, g, b, a in pal.colors:
        palette_bytes += [r, g, b, a]
    palette_bytes += [0] * ((256 - len(pal.colors)) * 4)

    with OUT.open("w") as f:
        f.write("// GENERATED by tools/c34_assets.py — do not edit.\n"
                "// CODEF screen 34 assets, halved to ST space, one shared palette.\n\n")
        f.write(f"#define FLAG_W {FLAG_W}\n#define FLAG_H {FLAG_H}\n"
                f"#define FLAG_FRAMES {FLAG_FRAMES}\n")
        f.write(f"#define LOGO_W {logo_w}\n#define LOGO_H {logo_h}\n")
        f.write(f"#define GLYPH {GLYPH}\n#define FIRST_CHAR {FIRST_CHAR}\n"
                f"#define NB_GLYPHS {NB_GLYPHS}\n\n")
        f.write(carray("PALETTE", palette_bytes, 16))
        f.write(carray("FLAG", flag))
        f.write(carray("LOGO", logo))
        f.write(carray("FONT", font))

    kb = OUT.stat().st_size / 1024
    print(f"{OUT}  ({kb:.0f} KB source)")
    print(f"  palette : {len(pal.colors)} colours (index 0 transparent)")
    print(f"  flag    : {FLAG_FRAMES} x {FLAG_W}x{FLAG_H} = {len(flag)} bytes")
    print(f"  logo    : {logo_w}x{logo_h} = {len(logo)} bytes")
    print(f"  font    : {NB_GLYPHS} x {GLYPH}x{GLYPH} = {len(font)} bytes")
    print(f"  data total: {(len(flag)+len(logo)+len(font))/1024:.0f} KB in the cart")


if __name__ == "__main__":
    main()
