#!/usr/bin/env python3
# Generate zigos/gem_glyphs.zig by EXTRACTING the real pixels of the GEM window
# control gadgets from the reference screenshot. The reference is a 2x-scaled
# low-res ST GEM window; we downsample to true logical pixels (perfectly 2x) and
# lift each 12x11 gadget box verbatim (frame + background + symbol). Stored as
# 1 = black ink, 0 = white paper, drawn 1:1 in gui.zig drawChrome.
#
# Source: window.png (put it next to this script or pass a path). Run:
#   python3 tools/gen_glyphs.py [path/to/window.png]
import sys
from PIL import Image

# Logical top-left of each 12x11 gadget box, found from the box separators in
# the reference (H lines at logical rows 0,10,20,78,88,98; V lines at cols
# 0,11,190,201,212). UP is the file-list area in this shot, so it is derived as
# the vertical mirror of DOWN (GEM draws them as mirror images).
BOXES = {
    "CLOSE": (0, 0),    # bowtie / X   (title, left)
    "FULL": (201, 0),   # diamond      (title, right)
    "DOWN": (201, 78),  # v-arrow      (right scrollbar, bottom)
    "SIZE": (201, 88),  # diagonal     (corner grow box)
    "LEFT": (0, 88),    # <-arrow      (bottom scrollbar, left)
    "RIGHT": (190, 88), # ->arrow      (bottom scrollbar, right)
}
GW, GH = 12, 11


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "window.png"
    im = Image.open(path).convert("L")
    px = im.load()

    def ink(lx, ly):  # logical pixel -> reference is exactly 2x
        return 1 if px[lx * 2, ly * 2] < 75 else 0

    def extract(x0, y0):
        rows = []
        for y in range(y0, y0 + GH):
            v = 0
            for x in range(x0, x0 + GW):
                if ink(x, y):
                    v |= 1 << (GW - 1 - (x - x0))
            rows.append(v)
        return rows

    glyphs = {name: extract(*xy) for name, xy in BOXES.items()}
    glyphs["UP"] = list(reversed(glyphs["DOWN"]))  # mirror of DOWN

    order = ["CLOSE", "FULL", "UP", "DOWN", "SIZE", "LEFT", "RIGHT"]
    out = [
        "// GENERATED by tools/gen_glyphs.py — real pixels lifted from the ST GEM window reference.",
        "// GEM window-control gadgets, 12x11, bit 11 = leftmost column. 1 = BLACK, 0 = WHITE.",
        "// Each is a complete box (frame + background + symbol); drawn 1:1 by gui.zig drawChrome.",
        f"pub const GW: u16 = {GW};",
        f"pub const GH: u16 = {GH};",
    ]
    for name in order:
        body = ", ".join(f"0x{v:03x}" for v in glyphs[name])
        out.append(f"pub const {name} = [GH]u16{{ {body} }};")
    with open("zigos/gem_glyphs.zig", "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote zigos/gem_glyphs.zig from", path)


if __name__ == "__main__":
    main()
