#!/usr/bin/env python3
# Generate zigos/gem_glyphs.zig — GEM window-control glyphs (close bowtie, full
# diamond, scrollbar arrows, size box) traced from the authentic low-res ST GEM
# window reference (scratchpad/win.png). 11x11, 1bpp, drawn centred in a control
# box so the box face shows through the 0 pixels. Run: python3 tools/gen_glyphs.py
GLYPHS = {
    "CLOSE": [  # filled bowtie / X (close box)
        "11000000011", "11100000111", "01110001110", "00111011100",
        "00011111000", "00001110000", "00011111000", "00111011100",
        "01110001110", "11100000111", "11000000011",
    ],
    "FULL": [  # diamond outline + centre dot (full / grow box)
        "00000100000", "00001110000", "00011011000", "00110001100",
        "01100000110", "11001110011", "01100000110", "00110001100",
        "00011011000", "00001110000", "00000100000",
    ],
    "UP": [
        "00000100000", "00001110000", "00011111000", "00111111100",
        "01111111110", "00011111000", "00011111000", "00011111000",
        "00011111000", "00000000000", "00000000000",
    ],
    "DOWN": [
        "00000000000", "00000000000", "00011111000", "00011111000",
        "00011111000", "00011111000", "01111111110", "00111111100",
        "00011111000", "00001110000", "00000100000",
    ],
    "LEFT": [
        "00000000000", "00001000000", "00011000000", "00111000000",
        "01111111100", "11111111100", "01111111100", "00111000000",
        "00011000000", "00001000000", "00000000000",
    ],
    "RIGHT": [
        "00000000000", "00000010000", "00000011000", "00000011100",
        "00111111110", "00111111111", "00111111110", "00000011100",
        "00000011000", "00000010000", "00000000000",
    ],
    "SIZE": [  # "/" diagonal staircase (size / grow box)
        "00000000110", "00000001110", "00000011100", "00000111000",
        "00001110000", "00011100000", "00111000000", "01110000000",
        "11100000000", "11000000000", "00000000000",
    ],
}


def encode(art):
    rows = []
    for line in art:
        v = 0
        for i, ch in enumerate(line):
            if ch == "1":
                v |= 1 << (10 - i)
        rows.append(v)
    return rows


def main():
    out = [
        "// GENERATED by tools/gen_glyphs.py from the ST GEM window reference — do not hand-edit.",
        "// GEM window-control glyphs, 11x11, bit 10 = leftmost column, 1 = ink pixel.",
        "// Drawn centred in a control box (0 pixels leave the box face showing through).",
        "pub const GW: u16 = 11;",
        "pub const GH: u16 = 11;",
    ]
    for name, art in GLYPHS.items():
        body = ", ".join(f"0x{v:03x}" for v in encode(art))
        out.append(f"pub const {name} = [GH]u16{{ {body} }};")
    with open("zigos/gem_glyphs.zig", "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote zigos/gem_glyphs.zig")


if __name__ == "__main__":
    main()
