#!/usr/bin/env python3
"""Assets for ULM's Parallax Distorter (Dark Side of the Spoon), CODEF screen 287.

    python3 tools/ulm_spoon_distorter_assets.py

Reads the fetched reference in prototypes/codef/287/ (tools/fetch_codef.py 287).

Both PNGs are ALREADY 1x: the remake builds its offscreens at the 384x270 logical
size and only zooms the final drawPart by 2. A 4-way 2x2 test finds no doubling
grid in either image, so nothing is halved.

Outputs (apps/zig/assets/screens/ulm_spoon_distorter/):
    back.raw        8x168    back.png, indices 1..27 of screen_pal (its black is OPAQUE)
    font.raw        320x200  font.png, 0 = transparent (tRNS index 0, the dark red
                             field), ink 1..8 -> screen_pal 28..35 (its black is ink)
    screen_pal.dat           0 transparent, 1..27 back.png, 28..35 font.png ink
Generated source (apps/zig/scenes/ulm_spoon_distorter/tables.zig):
    the wave delta tables, the four wave sequences, the letter table and the
    scrolltext, copied verbatim out of screen.js.
Music (docs/music/ulm_spoon_distorter_you.raw):
    you-low.wav (8-bit unsigned mono 8000 Hz) resampled to the host's 12517 Hz,
    signed.
"""
from __future__ import annotations

import re
import struct
import wave
from pathlib import Path

from PIL import Image

SRC = Path("prototypes/codef/287")
DST = Path("apps/zig/assets/screens/ulm_spoon_distorter")
TABLES = Path("apps/zig/scenes/ulm_spoon_distorter/tables.zig")
MUSIC = Path("docs/music/ulm_spoon_distorter_you.raw")
HOST_RATE = 12517
FONT_BASE = 27  # font ink index k lands at FONT_BASE + k
DELTAS = ("boink", "slowsin", "slowdist", "fast", "sinschief", "wordhinher", "nix", "dreieck", "bigsin", "fuzzy")
SEQUENCES = ("front_intro_wave_table", "front_main_wave_table", "back_intro_wave_table", "back_main_wave_table")


def images() -> None:
    back = Image.open(SRC / "assets/back.png")
    font = Image.open(SRC / "assets/font.png")
    if back.mode != "P" or back.size != (8, 168):
        raise SystemExit(f"back.png: {back.mode} {back.size}, expected P 8x168")
    if font.mode != "P" or font.size != (320, 200) or font.info.get("transparency") != 0:
        raise SystemExit("font.png: expected P 320x200 with tRNS index 0")
    bp, fp = back.getpalette(), font.getpalette()
    back_used = max(back.getdata())
    font_used = max(font.getdata())
    if back_used + 1 > FONT_BASE or FONT_BASE + font_used > 255:
        raise SystemExit(f"palette budget: back uses {back_used + 1}, font {font_used}")
    pal = [(0, 0, 0, 0)]
    pal += [(*bp[i * 3 : i * 3 + 3], 255) for i in range(FONT_BASE)]
    pal += [(*fp[k * 3 : k * 3 + 3], 255) for k in range(1, font_used + 1)]
    flat = [v for c in pal for v in c] + [0] * ((256 - len(pal)) * 4)
    (DST / "screen_pal.dat").write_bytes(struct.pack("1024B", *flat))
    (DST / "back.raw").write_bytes(bytes(i + 1 for i in back.getdata()))
    (DST / "font.raw").write_bytes(bytes(0 if k == 0 else FONT_BASE + k for k in font.getdata()))
    print(f"  back.raw 8x168, font.raw 320x200, screen_pal.dat {len(pal)} entries")


def js_array(src: str, name: str) -> str:
    m = re.search(r"\b" + name + r" = \[(.*?)\n\s*\]", src, re.S)
    if m is None:
        raise SystemExit(f"screen.js: no table {name}")
    return m.group(1)


def zig_tables(src: str) -> str:
    out = [
        "// GENERATED by tools/ulm_spoon_distorter_assets.py from prototypes/codef/287/screen.js.",
        "// Every number and string is the remake's own, verbatim. Do not edit by hand.",
        "",
        "pub const Glyph = struct { c: u8, x: u16, y: u16, w: u16 };",
        "",
    ]
    for name in DELTAS:
        vals = re.findall(r"-?\d+", js_array(src, name))
        out.append(f"pub const {name} = [_]i8{{ {', '.join(vals)} }};")
    for name in SEQUENCES:
        refs = re.findall(r"'(\w+)'", js_array(src, name))
        out.append(f"pub const {name} = [_][]const i8{{ {', '.join('&' + r for r in refs)} }};")
    letters = re.findall(r"\[(\"'\"|'.'),\s*(\d+),\s*(\d+),\s*(\d+)\]", js_array(src, "letter"))
    out.append("pub const letter = [_]Glyph{")
    for ch, x, y, w in letters:
        c = ch[1]
        lit = "'\\''" if c == "'" else f"'{c}'"
        out.append(f"    .{{ .c = {lit}, .x = {x}, .y = {y}, .w = {w} }},")
    out.append("};")
    m = re.search(r"text =\n(.*?);\n", src, re.S)
    if m is None:
        raise SystemExit("screen.js: no scrolltext")
    parts = re.findall(r"'((?:[^'\\]|\\.)*)'", m.group(1))
    text = "".join(p.replace("\\'", "'") for p in parts)
    if set(text) - {l[0][1] for l in letters}:
        raise SystemExit("scrolltext has a character with no glyph")
    out.append(f'pub const text = "{text.replace(chr(92), chr(92) * 2)}";')
    return "\n".join(out) + "\n"


def music() -> None:
    with wave.open(str(SRC / "assets/you-low.wav")) as w:
        if (w.getnchannels(), w.getsampwidth(), w.getframerate()) != (1, 1, 8000):
            raise SystemExit("you-low.wav: expected 8-bit mono 8000 Hz")
        data = w.readframes(w.getnframes())
    n = len(data) * HOST_RATE // 8000
    out = bytearray(n)
    for i in range(n):
        pos = i * 8000 / HOST_RATE
        j = int(pos)
        a = data[j]
        b = data[j + 1] if j + 1 < len(data) else data[j]
        v = round(a + (b - a) * (pos - j)) - 128
        out[i] = v & 0xFF
    MUSIC.write_bytes(bytes(out))
    print(f"  {MUSIC}: {len(data)} frames @8000 -> {n} @{HOST_RATE} ({n / HOST_RATE:.3f} s)")


if __name__ == "__main__":
    if not SRC.is_dir():
        raise SystemExit(f"missing {SRC} (run tools/fetch_codef.py 287)")
    DST.mkdir(parents=True, exist_ok=True)
    TABLES.parent.mkdir(parents=True, exist_ok=True)
    print(f"ULM PARALLAX DISTORTER (CODEF 287) -> {DST}")
    images()
    TABLES.write_text(zig_tables((SRC / "screen.js").read_text()))
    print(f"  {TABLES}")
    music()
